/*
 * qnn_collect_main.c (qw) — Main loop for the QW demo worker.
 *
 * QW equivalent of nq/qnn_collect_main.c.  Handles two demo formats:
 *
 *   QWD (client-side): dem_cmd messages contain usercmd_t with the
 *     player's exact inputs — ground truth labels.
 *
 *   MVD (server-side): No usercmd_t.  All player state is visible.
 *     Actions are inferred from position/angle/state deltas using the
 *     same approach as the NQ worker: 9-candidate BSP physics for
 *     movement (via QW pmove), sound/state cues for fire/jump.
 *
 * Client state sync via QNN_SyncEngineCompat() each frame.
 * Output format is identical to the NQ worker (QOBS framed binary)
 * so bc_collect.py can consume it directly.
 */

#include "qnn.h"
#include "qnn_io.h"
#include "qnn_store.h"
#include "qnn_metrics.h"

#include <stdlib.h>
#include <string.h>

#define QNN_WORKER_PROTOCOL "v6"
#define QNN_WORKER_SERVER_NAME "qw-demo-worker"
#define QNN_WORKER_UPSTREAM_COMMIT "bf4ac424ce754894ac8f1dae6a3981954bc9852d"
#define QNN_WORKER_MAX_LINE 8192
#define QNN_WORKER_MAX_COMMAND_TEXT 1024

/* Engine-compat sync — defined in qnn_engine_compat.c, generated by the
 * QW build script.  Mirrors the QW client's playernum/time/scoreboard
 * into the NQ-flavor fields the shared worker code reads. */
extern void QNN_SyncEngineCompat(void);
extern void QNN_SyncBaselines(void);

/* ── Match state from svc_print text ──────────────────────────── */

/* Match state defined in common/qnn_match.c. */
extern int qnn_match_state;
extern const char *qnn_match_log_tag;

/* Per-native-frame origin buffer for physics inference. */
#define QNN_MAX_NATIVE_FRAMES 16
#define QNN_TELEPORT_DIST_SQ (400.0f * 400.0f)
#define QNN_MAX_PUSH_TRIGGERS 8

/* Emission-level frame filters (matches NQ). */
#define QNN_GOD_MODE_HEALTH     250
#define QNN_DEAD_MAX_EMIT       20   /* 1 s at 20 Hz */
#define QNN_FROZEN_MAX_EMIT     40   /* 2 s at 20 Hz */

typedef struct
{
	int	fixed_tick_hz;
	float	fixed_dt;
	int	resample_hz;
	int	tick;
	int	steps;
	qboolean has_reset;
	qboolean done;
	vec3_t	prev_origin;
	vec3_t	prev_velocity;
	int	prev_ammo;
	qboolean has_prev;
	vec3_t	emit_view_angles;
	vec3_t	emit_origin;
	vec3_t	emit_velocity;
	qboolean emit_grounded;
	int	emit_waterlevel;
	int	emit_weapon_id;
	qboolean has_emit_anchor;
	int	native_frame_count;
	/* Mover tracking. */
	int	mover_entity_nums[QNN_MAX_PHYS_MOVERS];
	int	mover_model_indices[QNN_MAX_PHYS_MOVERS];
	int	mover_count;
	vec3_t	mover_emit_origins[QNN_MAX_PHYS_MOVERS];
	vec3_t	mover_origins[QNN_MAX_NATIVE_FRAMES][QNN_MAX_PHYS_MOVERS];
	/* Other player positions for body-block collision. */
	vec3_t	player_origins[QNN_MAX_NATIVE_FRAMES][QNN_MAX_PHYS_PLAYERS];
	int	player_entity_nums[QNN_MAX_PHYS_PLAYERS];
	int	player_count;
	/* trigger_push tracking. */
	int	push_model_indices[QNN_MAX_PUSH_TRIGGERS];
	vec3_t	push_velocities[QNN_MAX_PUSH_TRIGGERS];
	int	push_count;
	/* Previous candidate direction for continuity bias. */
	int	prev_fwd_sign;
	int	prev_strafe_sign;
	float	prev_move[3];
	/* Previous valid weapon impulse (1-8) seen.  Used for edge-detection
	 * on switch_slot — some QWD recorders write the held weapon every
	 * frame instead of leaving impulse=0 between presses, so we only
	 * emit switch when the weapon impulse value changes. */
	int	prev_weapon_impulse;
	qboolean has_prev_weapon_impulse;
	FILE	*store_dump;
	qnn_tick_emit_state_t tick_emit;
	/* Frame filter counters. */
	int	dead_emit_count;
	int	frozen_emit_count;
} qnn_runtime_t;

static qnn_runtime_t qnn_runtime;

static qboolean QNN_ClientReady(void)
{
	/* QW uses ca_active instead of ca_connected + SIGNONS */
	return (cls.demoplayback
		&& cls.state == ca_active
		&& cl.worldmodel != NULL
		&& cl.playernum >= 0
		&& cl.playernum < MAX_CLIENTS) ? true : false;
}

/* Build mover/push/player refs into the runtime via shared scanners
 * in common/qnn_collect_helpers.c. */
static void QNN_BuildAllRefs(void)
{
	qnn_runtime.mover_count = QNN_BuildMoverRefs(
		qnn_runtime.mover_entity_nums,
		qnn_runtime.mover_model_indices,
		QNN_MAX_PHYS_MOVERS);
	qnn_runtime.push_count = QNN_BuildPushRefs(
		qnn_runtime.push_model_indices,
		qnn_runtime.push_velocities,
		QNN_MAX_PUSH_TRIGGERS);
	qnn_runtime.player_count = QNN_BuildPlayerRefs(
		cl.playernum + 1,	/* QW: tracked player's entity */
		qnn_runtime.player_entity_nums,
		QNN_MAX_PHYS_PLAYERS);
	if (qnn_runtime.mover_count > 0)
		fprintf(stderr, "[qw-demo] tracking %d movers for physics baseline\n",
			qnn_runtime.mover_count);
	if (qnn_runtime.push_count > 0)
		fprintf(stderr, "[qw-demo] tracking %d push triggers for velocity subtraction\n",
			qnn_runtime.push_count);
	if (qnn_runtime.player_count > 0)
		fprintf(stderr, "[qw-demo] tracking %d other players for body-block collision\n",
			qnn_runtime.player_count);
}

/* ── Action extraction from QWD usercmd_t ────────────────────── */

/* In QWD demos, dem_cmd messages contain usercmd_t with:
 *   forwardmove, sidemove, upmove (short)
 *   buttons (byte) — BUTTON_ATTACK = 1, BUTTON_JUMP = 2
 *   impulse (byte) — weapon select impulse
 *   angles[3] (float) — view angles
 *
 * We extract these directly rather than inferring from physics. */
static void QNN_ExtractActionFromUsercmd(qnn_action_t *action)
{
	usercmd_t *cmd;
	int seq;

	QNN_ClearAction(action);

	if (cls.netchan.outgoing_sequence <= 0)
		return;

	seq = (cls.netchan.outgoing_sequence - 1) & UPDATE_MASK;
	cmd = &cl.frames[seq].cmd;

	/* Movement: normalize by maxspeed (default 320) */
	action->move[0] = QNN_Clamp((float)cmd->forwardmove / QNN_SV_MAXSPEED, -1.0f, 1.0f);
	action->move[1] = QNN_Clamp((float)cmd->sidemove / QNN_SV_MAXSPEED, -1.0f, 1.0f);

	/* Fire: BUTTON_ATTACK = bit 0 */
	action->fire = (cmd->buttons & 1) ? 1 : 0;

	/* move[2]: jump (positive) and swim-down (negative).
	 * Jump button or +moveup: positive jump speed.
	 * +movedown (upmove < 0): negative, capturing swim down in water. */
	if ((cmd->buttons & 2) || cmd->upmove > 0)
		action->move[2] = QNN_SV_JUMP_SPEED / QNN_SV_MAXSPEED;
	else if (cmd->upmove < 0)
		action->move[2] = QNN_Clamp((float)cmd->upmove / QNN_SV_MAXSPEED, -1.0f, 0.0f);

	/* Weapon switch: impulse 1-8 maps to weapon slots, but only on the
	 * EDGE between two different weapon impulses.  Some QWD recorders
	 * write the held weapon into impulse every frame instead of just
	 * on the press, so we'd emit switch every frame if we treated the
	 * raw value as the event.  Tracking the previous *weapon* impulse
	 * (ignoring zero / non-weapon impulses like 9, 10, 20) collapses
	 * both the event-style and state-style files to the same semantics:
	 * emit switch only when the player picks a different weapon. */
	{
		int imp = (int)cmd->impulse;
		if (imp >= 1 && imp <= 8) {
			if (qnn_runtime.has_prev_weapon_impulse
				&& imp != qnn_runtime.prev_weapon_impulse)
				action->switch_slot = QNN_SwitchSlotFromWeaponId(imp);
			qnn_runtime.prev_weapon_impulse = imp;
			qnn_runtime.has_prev_weapon_impulse = true;
		}
	}
}

/* ── View-relative look label ────────────────────────────────── */

/* Fill action->look (view-relative turn delta) and action->switch_slot
 * (weapon change since last emit) from the current snapshot relative to
 * the saved emit anchor.  Shared by both the QWD and MVD paths — only
 * the movement/fire source differs between them.  Does not touch
 * switch_slot if the caller has already set it (QWD path extracts from
 * usercmd->impulse first). */
static void QNN_FillLookAndSwitch(qnn_action_t *action,
	const qnn_snapshot_t *snapshot)
{
	vec3_t forward, right, up, cur_forward;

	if (!qnn_runtime.has_emit_anchor)
		return;

	AngleVectors(qnn_runtime.emit_view_angles, forward, right, up);
	QNN_ForwardFromAngles(snapshot->player_view_angles, cur_forward);
	action->look[0] = DotProduct(cur_forward, forward);
	action->look[1] = DotProduct(cur_forward, right);
	action->look[2] = DotProduct(cur_forward, up);

	if (action->switch_slot == 0
		&& snapshot->weapon_id != qnn_runtime.emit_weapon_id
		&& snapshot->weapon_id > 0)
		action->switch_slot = QNN_SwitchSlotFromWeaponId(snapshot->weapon_id);
}

/* QWD emission: movement/fire/jump read from the usercmd in the
 * most-recent dem_cmd frame; look/switch inferred from state. */
static void QNN_InferEmitAction(qnn_action_t *action, const qnn_snapshot_t *snapshot)
{
	QNN_ExtractActionFromUsercmd(action);
	QNN_FillLookAndSwitch(action, snapshot);
}

/* ── MVD action inference (no usercmd_t available) ───────────── */

/* Per-frame fire detection for MVD demos — matches NQ. */
static void QNN_InferNativeAction_MVD(qnn_action_t *action,
	const qnn_snapshot_t *snapshot)
{
	QNN_ClearAction(action);

	if (!qnn_runtime.has_prev)
		return;

	action->fire = (QNN_SnapshotHasSelfWeaponFireSound(snapshot)
		|| snapshot->ammo < qnn_runtime.prev_ammo) ? 1 : 0;
}

/* MVD emission: only look/switch from state (movement filled separately
 * by QNN_InferEmitMove_MVD via 9-candidate physics). */
static void QNN_InferEmitAction_MVD(qnn_action_t *action,
	const qnn_snapshot_t *snapshot)
{
	QNN_ClearAction(action);
	QNN_FillLookAndSwitch(action, snapshot);
}

/* Per-emission movement labels for MVD demos.
 * 9-candidate BSP physics — feature parity with NQ InferEmitMove. */
static void QNN_InferEmitMove_MVD(qnn_action_t *action,
	const qnn_snapshot_t *snapshot, float emit_dt)
{
	int fwd_sign, strafe_sign;
	float raw[3];
	int medium, i;

	if (!qnn_runtime.has_emit_anchor || emit_dt <= 0.0f)
		return;

	/* Set up movers at emission-start positions + velocities. */
	if (qnn_runtime.mover_count > 0)
	{
		qnn_mover_state_t ms[QNN_MAX_PHYS_MOVERS];
		int m;
		for (m = 0; m < qnn_runtime.mover_count; m++)
		{
			int nf = qnn_runtime.native_frame_count;
			float *mend = (nf > 0) ? qnn_runtime.mover_origins[nf - 1][m]
				: qnn_runtime.mover_emit_origins[m];
			ms[m].model_index = qnn_runtime.mover_model_indices[m];
			VectorCopy(qnn_runtime.mover_emit_origins[m], ms[m].origin);
			for (i = 0; i < 3; i++)
				ms[m].velocity[i] = (mend[i] - qnn_runtime.mover_emit_origins[m][i]) / emit_dt;
		}
		QNN_PhysSetupMovers(ms, qnn_runtime.mover_count);
	}

	/* Set up other players at mid-window positions. */
	if (qnn_runtime.player_count > 0)
	{
		int nf = qnn_runtime.native_frame_count;
		int mid = (nf > 0) ? nf / 2 : 0;
		if (mid < nf)
			QNN_PhysSetupPlayers(qnn_runtime.player_origins[mid],
				qnn_runtime.player_count);
	}

	/* Run 9 candidates over the full emission window. */
	{
		qboolean unreachable;
		QNN_PhysBestCandidate(
			qnn_runtime.emit_velocity, qnn_runtime.emit_origin,
			qnn_runtime.emit_view_angles, qnn_runtime.emit_grounded,
			qnn_runtime.emit_waterlevel, emit_dt,
			snapshot->player_origin,
			qnn_runtime.prev_fwd_sign, qnn_runtime.prev_strafe_sign,
			&fwd_sign, &strafe_sign, &unreachable);

		/* External force (knockback, trigger_push, mover carry, or a
		 * server-side correction we can't reproduce) moved the player
		 * beyond what any input can explain — carry forward the last
		 * decision rather than letting the best-of-bad-options pick a
		 * wrong direction. */
		if (unreachable)
		{
			fwd_sign = qnn_runtime.prev_fwd_sign;
			strafe_sign = qnn_runtime.prev_strafe_sign;
		}
	}
	qnn_runtime.prev_fwd_sign = fwd_sign;
	qnn_runtime.prev_strafe_sign = strafe_sign;

	/* Convert candidate signs to raw move vector for QNN_SnapMove. */
	raw[0] = (float)fwd_sign;
	raw[1] = (float)strafe_sign;

	/* Z: use raw position delta for water, or 0 for ground/air. */
	{
		vec3_t delta, rel;
		for (i = 0; i < 3; i++)
			delta[i] = (snapshot->player_origin[i] - qnn_runtime.emit_origin[i]) / emit_dt;
		QNN_RelativeFrame(qnn_runtime.emit_view_angles, delta, rel);
		raw[2] = rel[2] / QNN_SV_MAXSPEED;
	}

	if (qnn_runtime.emit_waterlevel >= 2)
		medium = QNN_MEDIUM_WATER;
	else if (qnn_runtime.emit_grounded)
		medium = QNN_MEDIUM_GROUND;
	else
		medium = QNN_MEDIUM_AIR;

	QNN_SnapMove(raw, medium,
		QNN_SnapshotHasSelfJumpSound(snapshot),
		action->move);
}

/* ── Emit one tick ─────────────────────────────────────────────── */

/* QNN_EmitTick, QNN_JitterFilter, QNN_ActionIsFrozen, QNN_WriteObsTick,
 * QNN_FlushTickEmit — shared in common/qnn_collect_helpers.c. */

static FILE *QNN_EmitFilter(qnn_snapshot_t *snapshot)
{
	int health = snapshot->health;

	if (snapshot->done)
	{
		qnn_runtime.dead_emit_count = 0;
		qnn_runtime.frozen_emit_count = 0;
		return stdout;
	}

	/* God-mode (training): skip entirely. */
	if (health > QNN_GOD_MODE_HEALTH)
		return NULL;

	/* Dead: keep first QNN_DEAD_MAX_EMIT frames, inject fire=1, zero move. */
	if (health <= 0)
	{
		qnn_runtime.frozen_emit_count = 0;
		qnn_runtime.dead_emit_count++;
		if (qnn_runtime.dead_emit_count > QNN_DEAD_MAX_EMIT)
			return NULL;
		snapshot->action_label.fire = 1;
		snapshot->action_label.move[0] = 0.0f;
		snapshot->action_label.move[1] = 0.0f;
		snapshot->action_label.move[2] = 0.0f;
		return stdout;
	}

	qnn_runtime.dead_emit_count = 0;

	if (QNN_ActionIsFrozen(&snapshot->action_label))
	{
		qnn_runtime.frozen_emit_count++;
		if (qnn_runtime.frozen_emit_count > QNN_FROZEN_MAX_EMIT)
			return NULL;
		return stdout;
	}

	qnn_runtime.frozen_emit_count = 0;
	return stdout;
}

static void QNN_SavePrev(const qnn_snapshot_t *snapshot, float dt)
{
	if (qnn_runtime.has_prev && dt > 0.0f)
	{
		int i;
		for (i = 0; i < 3; i++)
			qnn_runtime.prev_velocity[i] =
				(snapshot->player_origin[i] - qnn_runtime.prev_origin[i]) / dt;
	}
	else
	{
		qnn_runtime.prev_velocity[0] = 0.0f;
		qnn_runtime.prev_velocity[1] = 0.0f;
		qnn_runtime.prev_velocity[2] = 0.0f;
	}
	VectorCopy(snapshot->player_origin, qnn_runtime.prev_origin);
	qnn_runtime.prev_ammo = snapshot->ammo;
	qnn_runtime.has_prev = true;
}

static void QNN_SaveEmitAnchor(const qnn_snapshot_t *snapshot)
{
	int m;
	qboolean have_simvel;

	VectorCopy(snapshot->player_view_angles, qnn_runtime.emit_view_angles);
	VectorCopy(snapshot->player_origin, qnn_runtime.emit_origin);

	/* Prefer the client-predicted simvel captured on the snapshot over
	 * the origin-delta approximation.  QW's CL_PredictMove runs the
	 * same pmove integrator the server used, so simvel is the
	 * instantaneous velocity at the emission moment — exactly what the
	 * 9-candidate physics needs as its starting velocity.  The
	 * origin-delta fallback (prev_velocity) averages over the previous
	 * 20 ms native tick, so it's a frame-old estimate that causes
	 * candidate endpoints to drift when the player is accelerating or
	 * decelerating. */
	have_simvel = (snapshot->player_velocity[0] != 0.0f
		|| snapshot->player_velocity[1] != 0.0f
		|| snapshot->player_velocity[2] != 0.0f);
	if (have_simvel)
	{
		VectorCopy(snapshot->player_velocity, qnn_runtime.emit_velocity);
	}
	else if (qnn_runtime.has_prev)
	{
		VectorCopy(qnn_runtime.prev_velocity, qnn_runtime.emit_velocity);
	}
	else
	{
		qnn_runtime.emit_velocity[0] = 0.0f;
		qnn_runtime.emit_velocity[1] = 0.0f;
		qnn_runtime.emit_velocity[2] = 0.0f;
	}
	qnn_runtime.emit_grounded = snapshot->grounded;
	qnn_runtime.emit_waterlevel = snapshot->waterlevel;
	qnn_runtime.emit_weapon_id = snapshot->weapon_id;
	qnn_runtime.native_frame_count = 0;
	/* Snapshot mover positions at emission anchor. */
	for (m = 0; m < qnn_runtime.mover_count; m++)
	{
		entity_t *me = &cl_entities[qnn_runtime.mover_entity_nums[m]];
		VectorCopy(me->origin, qnn_runtime.mover_emit_origins[m]);
	}
	qnn_runtime.has_emit_anchor = true;
}

static void QNN_RuntimeReset(void)
{
	const char *dump_path;

	memset(&qnn_runtime, 0, sizeof(qnn_runtime));
	qnn_runtime.fixed_tick_hz = 32;  /* QW default server fps — refined by detection */
	qnn_runtime.fixed_dt = 1.0f / 32.0f;
	qnn_runtime.store_dump = NULL;

	dump_path = getenv("QNN_STORE_DUMP");
	if (dump_path != NULL && dump_path[0] != '\0')
	{
		qnn_runtime.store_dump = fopen(dump_path, "w");
		if (qnn_runtime.store_dump != NULL)
			fprintf(stderr, "[qw-demo] store dump: %s\n", dump_path);
		else
			fprintf(stderr, "[qw-demo] store dump: failed to open %s\n", dump_path);
	}
}

/* Probe native recording tick rate by counting server messages received
 * over a short window.  QW's cl.time advances every Host_Frame (not per-
 * message like NQ's cl.mtime[0]), so we key off cls.netchan.incoming_sequence
 * which increments once per parsed server message. */
#define QNN_DEMO_DETECT_PROBE_DT 0.001f
#define QNN_DEMO_DETECT_MAX_FRAMES 2048
#define QNN_DEMO_DETECT_SAMPLES    8

static void QNN_DetectNativeTickHz(void)
{
	int start_seq;
	double start_time;
	double end_time;
	int end_seq;
	int frame;
	float native_dt;
	int detected_hz;
	int samples;

	/* Pump until the first new server message arrives, so start_time
	 * anchors to a real message boundary rather than mid-frame. */
	start_seq = cls.netchan.incoming_sequence;
	for (frame = 0; frame < QNN_DEMO_DETECT_MAX_FRAMES; ++frame)
	{
		Host_Frame(QNN_DEMO_DETECT_PROBE_DT);
		if (!cls.demoplayback || cls.state == ca_disconnected)
			return;
		if (cls.netchan.incoming_sequence != start_seq)
		{
			start_seq = cls.netchan.incoming_sequence;
			break;
		}
	}
	start_time = cl.time;

	/* Collect QNN_DEMO_DETECT_SAMPLES additional messages. */
	samples = 0;
	end_seq = start_seq;
	for (frame = 0; frame < QNN_DEMO_DETECT_MAX_FRAMES; ++frame)
	{
		Host_Frame(QNN_DEMO_DETECT_PROBE_DT);
		if (!cls.demoplayback || cls.state == ca_disconnected)
			return;
		if (cls.netchan.incoming_sequence != end_seq)
		{
			samples += cls.netchan.incoming_sequence - end_seq;
			end_seq = cls.netchan.incoming_sequence;
			if (samples >= QNN_DEMO_DETECT_SAMPLES)
				break;
		}
	}
	if (samples < 1)
		return;

	end_time = cl.time;
	if (end_time <= start_time)
		return;

	native_dt = (float)((end_time - start_time) / (double)samples);
	if (native_dt <= 0.001f || native_dt > 1.0f)
		return;

	detected_hz = (int)(1.0f / native_dt + 0.5f);
	if (detected_hz < 5 || detected_hz > 200)
		return;

	qnn_runtime.fixed_tick_hz = detected_hz;
	qnn_runtime.fixed_dt = 1.0f / (float)detected_hz;
	fprintf(stderr, "[qw-demo] detected native tick rate: %d Hz (dt=%.4fs, %d samples)\n",
		detected_hz, qnn_runtime.fixed_dt, samples);
}

static void QNN_CaptureSnapshotLocal(qnn_snapshot_t *snapshot, qboolean reset_flag)
{
	QNN_SyncEngineCompat();
	QNN_CaptureBaseSnapshot(snapshot);
	snapshot->done = reset_flag ? false : qnn_runtime.done;
	QNN_DrainSounds(snapshot);
}

static qboolean QNN_ResetWorldLocal(const char *demo_path, int seed, char *error, size_t error_size)
{
	char command[QNN_WORKER_MAX_COMMAND_TEXT];
	int frame;

	if (qnn_map_state.map_name[0] == 0)
	{
		snprintf(error, error_size, "Call hello first so the worker knows which map to load");
		return false;
	}
	if (demo_path == NULL || demo_path[0] == 0)
	{
		snprintf(error, error_size, "reset options must include demo_path");
		return false;
	}

	QNN_ClearAction(&qnn_pending_action);
	qnn_runtime.done = false;
	qnn_runtime.has_reset = false;
	qnn_sound_count = 0;
	cls.demonum = -1;
	cls.timedemo = false;

	CL_Disconnect();
	cls.state = ca_disconnected;

	/* Nuke any residual stufftext from the previous demo or
	 * Host_Init.  svc_stufftext messages in demos (cvar sets,
	 * disconnect, map loads) accumulate in cmd_text and would
	 * otherwise run before our playdemo, corrupting state. */
	{
		extern sizebuf_t cmd_text;
		SZ_Clear(&cmd_text);
	}

	snprintf(command, sizeof(command), "playdemo \"%s\"\n", demo_path);
	Cbuf_AddText(command);
	Cbuf_Execute();

	/* Pump frames until demo is loaded and active.  A working demo
	 * reaches ca_active within ~100 frames; if we haven't after 2048
	 * something is wrong (missing BSP, corrupt demo, etc.). */
	for (frame = 0; frame < 2048; ++frame)
	{
		Host_Frame(qnn_runtime.fixed_dt);
		if (QNN_ClientReady())
			break;
		if (frame > 0 && !cls.demoplayback && cls.state == ca_disconnected)
			break;
		/* Fail fast on missing BSP: QW parses the modellist early in
		 * signon, so cl.model_name[1] is set within a few frames. If
		 * that's set but cl.worldmodel is still NULL 256 frames later,
		 * Mod_ForName couldn't find the map file — no point pumping
		 * another 1792 frames waiting for ca_active. */
		if (frame >= 256 && cl.worldmodel == NULL && cl.model_name[1][0] != '\0')
		{
			fprintf(stderr, "[qw-demo] missing BSP: %s (worldmodel not loaded after %d frames)\n",
				cl.model_name[1], frame);
			snprintf(error, error_size, "Missing BSP %s for demo %s", cl.model_name[1], demo_path);
			return false;
		}
	}
	if (!QNN_ClientReady())
	{
		fprintf(stderr, "[qw-demo] playdemo failed: demoplayback=%d state=%d\n",
			cls.demoplayback, cls.state);
		/* Distinguish between "demo file exhausted during signon"
		 * (permanent: QWD preamble is corrupt / non-standard) and
		 * "engine got stuck" (possibly transient). Python uses the
		 * prefix to decide whether to retry. */
		if (!cls.demoplayback)
			snprintf(error, error_size,
				"demo_preamble_incompatible: %s (demoplayback ended during signon)",
				demo_path);
		else
			snprintf(error, error_size,
				"signon_timeout: %s (no ca_active after 2048 frames)",
				demo_path);
		return false;
	}

	/* Sync NQ compat state and baselines */
	QNN_SyncEngineCompat();
	QNN_SyncBaselines();

	/* Detect the actual recording rate (QWD servers vary 10–77 Hz,
	 * MVD is typically 77 Hz).  Probe before anything else timing-
	 * sensitive so QNN_ResampleInit and physics inference see the
	 * correct native dt. */
	QNN_DetectNativeTickHz();

	/* Detect actual map from worldmodel */
	if (cl.worldmodel != NULL && cl.worldmodel->name[0] != '\0')
	{
		char demo_map[QNN_MAX_MAP_ID];
		const char *bsp_name = cl.worldmodel->name;
		const char *slash;
		const char *dot;
		size_t len;

		slash = strrchr(bsp_name, '/');
		if (slash != NULL)
			bsp_name = slash + 1;
		dot = strrchr(bsp_name, '.');
		len = dot ? (size_t)(dot - bsp_name) : strlen(bsp_name);
		if (len >= sizeof(demo_map))
			len = sizeof(demo_map) - 1;
		memcpy(demo_map, bsp_name, len);
		demo_map[len] = '\0';

		if (strcasecmp(demo_map, qnn_map_state.map_name) != 0)
		{
			char map_error[256];
			if (!QNN_PrepareMap(demo_map, map_error, sizeof(map_error)))
				fprintf(stderr, "[qw-demo] map rebuild for %s failed: %s\n", demo_map, map_error);
		}
	}

	qnn_runtime.tick = 0;
	qnn_runtime.steps = 0;
	qnn_runtime.has_reset = true;
	qnn_runtime.done = false;
	QNN_IOInit(&qnn_map_state);
	return true;
}

static void QNN_WriteHelloResponse(void)
{
	fprintf(stdout, "{\"capabilities\":[\"demo_playback\",\"qw_demo\",\"mvd_demo\",\"navmesh_query_v1\",\"obs_buffer_collect_v1\"],\"map_id\":");
	QNN_WriteJsonString(stdout, qnn_map_state.requested_map_id);
	fprintf(stdout, ",\"ok\":true,\"protocol_version\":");
	QNN_WriteJsonString(stdout, QNN_WORKER_PROTOCOL);
	fprintf(stdout, ",\"server\":");
	QNN_WriteJsonString(stdout, QNN_WORKER_SERVER_NAME);
	fprintf(stdout, ",\"tick_hz\":%d,\"worker_build\":{\"basedir\":", qnn_runtime.fixed_tick_hz);
	QNN_WriteJsonString(stdout, basedir);
	fprintf(stdout, ",\"upstream_commit\":");
	QNN_WriteJsonString(stdout, QNN_WORKER_UPSTREAM_COMMIT);
	fprintf(stdout, "}}\n");
	fflush(stdout);
}

static int QNN_HandleHello(const char *line)
{
	char map_id[QNN_MAX_MAP_ID];
	char error[256];

	memset(map_id, 0, sizeof(map_id));
	memset(error, 0, sizeof(error));
	if (!QNN_JsonExtractString(line, "\"map_id\"", map_id, sizeof(map_id)))
		snprintf(map_id, sizeof(map_id), "dm3");

	qnn_runtime.resample_hz = QNN_JsonExtractInt(line, "\"resample_hz\"", 0);

	if (!QNN_PrepareMap(map_id, error, sizeof(error)))
	{
		QNN_WriteError(error);
		return 0;
	}

	QNN_WriteHelloResponse();
	return 0;
}

static int QNN_HandleCollect(const char *line)
{
	qnn_action_t native_action;
	qnn_snapshot_t snapshot;
	char demo_path[MAX_OSPATH];
	char error[256];
	int seed;
	int mvd_player_num;

	int play_start, play_end;

	memset(demo_path, 0, sizeof(demo_path));
	memset(error, 0, sizeof(error));
	seed = QNN_JsonExtractInt(line, "\"seed\"", -1);
	mvd_player_num = QNN_JsonExtractInt(line, "\"player_num\"", -1);
	play_start = QNN_JsonExtractInt(line, "\"play_start\"", 0);
	play_end = QNN_JsonExtractInt(line, "\"play_end\"", 999999999);
	qnn_match_state = 1; /* always emit — boundaries are frame-gated */
	if (!QNN_JsonExtractString(line, "\"demo_path\"", demo_path, sizeof(demo_path)))
	{
		QNN_WriteError("reset options must include demo_path");
		return 0;
	}
	if (!QNN_ResetWorldLocal(demo_path, seed, error, sizeof(error)))
	{
		QNN_WriteError(error);
		return 0;
	}

	/* MVD: select tracked player and initialize physics inference.
	 * Tick rate already detected in QNN_ResetWorldLocal via
	 * QNN_DetectNativeTickHz (~77 Hz on MVDSV, varies elsewhere). */
	if (cls.mvdplayback)
	{
		int p;

		/* Select player: use requested player_num or auto-select */
		if (mvd_player_num >= 0 && mvd_player_num < MAX_CLIENTS
			&& cl.players[mvd_player_num].name[0] != '\0')
		{
			cl.playernum = mvd_player_num;
		}
		else
		{
			for (p = 0; p < MAX_CLIENTS; p++)
			{
				if (cl.players[p].name[0] != '\0'
					&& !cl.players[p].spectator)
				{
					cl.playernum = p;
					break;
				}
			}
		}
		fprintf(stderr, "[qw-demo] MVD tracking player %d: %s\n",
			cl.playernum, cl.players[cl.playernum].name);

		/* Initialize BSP-clipped physics for movement inference */
		QNN_PhysInit();
	}

	QNN_ResampleInit(qnn_runtime.resample_hz);
	if (qnn_runtime.resample_hz > 0)
		fprintf(stderr, "[qw-demo] resample target: %d Hz (source: %d Hz)\n",
			qnn_runtime.resample_hz, qnn_runtime.fixed_tick_hz);

	{
		int emit_hz = qnn_resample.target_hz > 0
			? qnn_resample.target_hz : qnn_runtime.fixed_tick_hz;

		QNN_CaptureSnapshotLocal(&snapshot, true);
		QNN_SavePrev(&snapshot, 0.0f);
		QNN_SaveEmitAnchor(&snapshot);
		QNN_IOUpdate(&snapshot, qnn_runtime.fixed_dt, true);
		QNN_BuildAllRefs();

		{
			qboolean emitting = false;

		while (!qnn_runtime.done)
		{
			Host_Frame(qnn_runtime.fixed_dt);
			qnn_runtime.tick += 1;
			qnn_runtime.steps += 1;

			if (!cls.demoplayback || cls.state == ca_disconnected)
				qnn_runtime.done = true;

			/* Frame-gated emission: play_start..play_end from the
			 * offline analyzer.  Everything outside is skipped. */
			if (qnn_runtime.tick > play_end)
			{
				snapshot.done = true;
				qnn_runtime.done = true;
			}

			QNN_CaptureSnapshotLocal(&snapshot, false);

			if (!emitting && qnn_runtime.tick >= play_start)
			{
				emitting = true;
				QNN_IOUpdate(&snapshot, qnn_runtime.fixed_dt, true);
				QNN_ResampleInit(qnn_runtime.resample_hz);
				QNN_SaveEmitAnchor(&snapshot);
				fprintf(stderr, "[qw-demo] emitting from tick %d (play_start=%d play_end=%d)\n",
					qnn_runtime.tick, play_start, play_end);
				QNN_SavePrev(&snapshot, qnn_runtime.fixed_dt);
				continue;
			}

			if (!emitting && !qnn_runtime.done)
			{
				QNN_SavePrev(&snapshot, qnn_runtime.fixed_dt);
				continue;
			}

			QNN_IOUpdate(&snapshot, qnn_runtime.fixed_dt, false);

			if (qnn_runtime.store_dump != NULL)
			{
				QNN_StoreDumpSounds(qnn_runtime.store_dump, qnn_runtime.tick, &snapshot);
				QNN_StoreDumpTick(qnn_runtime.store_dump, qnn_runtime.tick, (float)cl.mtime[0]);
			}

			/* Buffer per-native-frame mover and other-player positions
			 * so the emission-time physics inference can set up the
			 * correct BSP collision state for the 9 candidates. */
			if (cls.mvdplayback && !snapshot.done)
			{
				int nf = qnn_runtime.native_frame_count;
				if (nf < QNN_MAX_NATIVE_FRAMES)
				{
					int m;
					for (m = 0; m < qnn_runtime.mover_count; m++)
					{
						entity_t *me = &cl_entities[qnn_runtime.mover_entity_nums[m]];
						VectorCopy(me->origin, qnn_runtime.mover_origins[nf][m]);
					}
					for (m = 0; m < qnn_runtime.player_count; m++)
					{
						entity_t *pe = &cl_entities[qnn_runtime.player_entity_nums[m]];
						VectorCopy(pe->origin, qnn_runtime.player_origins[nf][m]);
					}
					qnn_runtime.native_frame_count = nf + 1;
				}
			}

			/* Extract per-frame action */
			if (!snapshot.done)
			{
				if (cls.mvdplayback)
					QNN_InferNativeAction_MVD(&native_action,
						&snapshot);
				else
					QNN_ExtractActionFromUsercmd(&native_action);
			}
			else
				QNN_ClearAction(&native_action);

			QNN_ResampleAccumulate(&native_action, qnn_runtime.fixed_dt);
			while (QNN_ResampleShouldEmit() || qnn_runtime.done)
			{
				if (!snapshot.done)
				{
					if (cls.mvdplayback)
					{
						float phys_dt;
						QNN_InferEmitAction_MVD(
							&snapshot.action_label,
							&snapshot);
						phys_dt = qnn_runtime.native_frame_count
							* qnn_runtime.fixed_dt;
						if (phys_dt > 0.0f)
						{
							QNN_InferEmitMove_MVD(
								&snapshot.action_label,
								&snapshot, phys_dt);
							qnn_runtime.prev_move[0] = snapshot.action_label.move[0];
							qnn_runtime.prev_move[1] = snapshot.action_label.move[1];
							qnn_runtime.prev_move[2] = snapshot.action_label.move[2];
						}
						else
						{
							snapshot.action_label.move[0] = qnn_runtime.prev_move[0];
							snapshot.action_label.move[1] = qnn_runtime.prev_move[1];
							snapshot.action_label.move[2] = qnn_runtime.prev_move[2];
						}
					}
					else
					{
						QNN_InferEmitAction(
							&snapshot.action_label,
							&snapshot);
					}
				}
				else
					QNN_ClearAction(&snapshot.action_label);
				QNN_ResampleApplyActionMerge(&snapshot.action_label);
				{
					FILE *emit_out = QNN_EmitFilter(&snapshot);
					QNN_WriteObsTick(&qnn_runtime.tick_emit,
						emit_out, &snapshot, qnn_runtime.tick,
						qnn_runtime.steps, emit_hz, false);
				}
				if (!snapshot.done)
					QNN_SaveEmitAnchor(&snapshot);
				if (qnn_resample.target_hz <= 0 || qnn_runtime.done)
					break;
			}

			QNN_SavePrev(&snapshot, qnn_runtime.fixed_dt);
		}

		QNN_FlushTickEmit(&qnn_runtime.tick_emit);

		if (!emitting)
		{
			/* Demo ended before play_start was reached — emit a
			 * done marker so the reader doesn't block. */
			snapshot.done = true;
			QNN_WriteObsTick(&qnn_runtime.tick_emit, stdout,
				&snapshot, qnn_runtime.tick,
				qnn_runtime.steps, emit_hz, true);
		}
		}
	}
	fflush(stdout);
	if (qnn_runtime.store_dump != NULL)
	{
		fflush(qnn_runtime.store_dump);
		fclose(qnn_runtime.store_dump);
		qnn_runtime.store_dump = NULL;
	}
	return 0;
}

int main(int argc, char **argv)
{
	quakeparms_t parms;
	char line[QNN_WORKER_MAX_LINE];

	qnn_match_log_tag = "[qw-demo]";
	QNN_ResolveBasedir(qnn_basedir_storage, sizeof(qnn_basedir_storage));
	QNN_RuntimeReset();
	QNN_ClearAction(&qnn_pending_action);
	memset(&parms, 0, sizeof(parms));
	COM_InitArgv(argc, argv);
	parms.argc = com_argc;
	parms.argv = com_argv;
	parms.memsize = 32 * 1024 * 1024;
	parms.membase = malloc(parms.memsize);
	parms.basedir = basedir;
	Host_Init(&parms);

	/* QW's Host_Init runs quake.rc which may connect somewhere.
	 * Disconnect and reset state for worker mode. */
	Cbuf_Execute();
	cls.demonum = -1;
	CL_Disconnect();
	cls.state = ca_disconnected;

	while (fgets(line, sizeof(line), stdin) != NULL)
	{
		if (strstr(line, "\"op\"") != NULL && strstr(line, "hello") != NULL)
		{
			QNN_HandleHello(line);
			continue;
		}
		if (strstr(line, "\"op\"") != NULL && strstr(line, "nav_query") != NULL)
		{
			QNN_HandleNavQuery(line);
			continue;
		}
		if (strstr(line, "\"op\"") != NULL && strstr(line, "collect") != NULL)
		{
			QNN_HandleCollect(line);
			continue;
		}
		if (strstr(line, "\"op\"") != NULL && strstr(line, "shutdown") != NULL)
		{
			fprintf(stdout, "{\"ok\":true}\n");
			fflush(stdout);
			QNN_FreeMapState(&qnn_map_state);
			Host_Shutdown();
			return 0;
		}
	}

	QNN_FreeMapState(&qnn_map_state);
	Host_Shutdown();
	return 0;
}
