/*
 * qnn_collect_main.c (qw) — Main loop for the QW demo worker.
 *
 * QW equivalent of nq/qnn_collect_main.c.  Handles two demo formats:
 *
 *   QWD (client-side): dem_cmd messages contain usercmd_t with the
 *     player's exact inputs — ground truth labels.
 *
 *   MVD (server-side): No usercmd_t.  All player state is visible.
 *     Actions are inferred from position/angle/state deltas using the
 *     same approach as the NQ worker: 9-candidate BSP physics for
 *     movement (via QW pmove), sound/state cues for fire/jump.
 *
 * Client state sync via QNN_SyncEngineCompat() each frame.
 * Output format is identical to the NQ worker (QOBS framed binary)
 * so bc_collect.py can consume it directly.
 */

#include "qnn.h"
#include "qnn_collect_helpers.h"
#include "qnn_mvd_collect.h"
#include "qnn_qwd_collect.h"
#include "qnn_labeler_collect.h"
#include "qnn_fault.h"
#include "qnn_io.h"
#include "qnn_store.h"
#include "qnn_metrics.h"
#include "qnn_watchdog.h"
#include "qnn_tick.h"

#include <stdlib.h>
#include <string.h>

#define QNN_WORKER_SERVER_NAME "qw-demo-worker"

/* Engine-compat sync — defined in qnn_engine_compat.c, generated by the
 * QW build script.  Mirrors the QW client's playernum/time/scoreboard
 * into the NQ-flavor fields the shared worker code reads. */
extern void QNN_SyncEngineCompat(void);
extern void QNN_SyncBaselines(void);
/* Per-frame entity visibility refresh — clears cl_entities[].model
 * for non-PVS slots so the shared QNN_EntityClassifyKnown walk sees
 * the same universe a normal NQ client would.  See qnn_engine_compat.c. */
extern void QNN_SyncPacketEntities(void);

#define QNN_TELEPORT_DIST_SQ (400.0f * 400.0f)

static qboolean QNN_ClientReady(void)
{
	/* QW uses ca_active instead of ca_connected + SIGNONS */
	return (cls.demoplayback
		&& cls.state == ca_active
		&& cl.worldmodel != NULL
		&& cl.playernum >= 0
		&& cl.playernum < MAX_CLIENTS) ? true : false;
}

/* Build mover/push/player refs into the runtime via shared scanners
 * in common/qnn_collect_helpers.c. */
static void QNN_BuildAllRefs(void)
{
	qnn_runtime.mover_count = QNN_BuildMoverRefs(
		qnn_runtime.mover_entity_nums,
		qnn_runtime.mover_model_indices,
		QNN_MAX_PHYS_MOVERS);
	qnn_runtime.push_count = QNN_BuildPushRefs(
		qnn_runtime.push_model_indices,
		qnn_runtime.push_velocities,
		QNN_MAX_PUSH_TRIGGERS);
	qnn_runtime.player_count = QNN_BuildPlayerRefs(
		cl.playernum + 1,	/* QW: tracked player's entity */
		qnn_runtime.player_entity_nums,
		QNN_MAX_PHYS_PLAYERS);
	if (qnn_runtime.mover_count > 0)
		fprintf(stderr, "[qw-demo] tracking %d movers for physics baseline\n",
			qnn_runtime.mover_count);
	if (qnn_runtime.push_count > 0)
		fprintf(stderr, "[qw-demo] tracking %d push triggers for velocity subtraction\n",
			qnn_runtime.push_count);
	if (qnn_runtime.player_count > 0)
		fprintf(stderr, "[qw-demo] tracking %d other players for body-block collision\n",
			qnn_runtime.player_count);
}

/* ── Action extraction from QWD usercmd_t ─────────────────────────
 *
 * QWD demos carry dem_cmd messages with usercmd_t (forwardmove, sidemove,
 * upmove, buttons, impulse, angles).  The cmd-window walker that
 * aggregates these into a single emit-rate action label lives in
 * src/engine/qw/qnn_qwd_collect.c.  See QNN_QwdExtractAction /
 * QNN_QwdInferEmitAction.
 */


/* ── MVD action inference ─────────────────────────────────────────
 *
 * Used on real MVD demos (cls.mvdplayback) or `force_mvd_emit` QWDs —
 * paths where no usercmd_t ground truth is available.  Lives in
 * src/engine/common/qnn_mvd_collect.c.  See QNN_MvdInferNativeAction /
 * QNN_MvdInferEmitAction / QNN_MvdInferEmitMove.
 */

/* ── Emit one tick ─────────────────────────────────────────────── */

/* QNN_EmitTick, QNN_JitterFilter, QNN_ActionIsFrozen, QNN_WriteObsTick,
 * QNN_FlushTickEmit, QNN_EmitFilter, QNN_SavePrev — shared in
 * common/qnn_collect_helpers.c. */

static void QNN_SaveEmitAnchor(const qnn_snapshot_t *snapshot)
{
	int m;
	qboolean have_simvel;

	VectorCopy(snapshot->player_view_angles, qnn_runtime.emit_view_angles);
	VectorCopy(snapshot->player_origin, qnn_runtime.emit_origin);

	/* Prefer the client-predicted simvel captured on the snapshot over
	 * the origin-delta approximation.  QW's CL_PredictMove runs the
	 * same pmove integrator the server used, so simvel is the
	 * instantaneous velocity at the emission moment — exactly what the
	 * 9-candidate physics needs as its starting velocity.  The
	 * origin-delta fallback (prev_velocity) averages over the previous
	 * 20 ms native tick, so it's a frame-old estimate that causes
	 * candidate endpoints to drift when the player is accelerating or
	 * decelerating. */
	have_simvel = (snapshot->player_velocity[0] != 0.0f
		|| snapshot->player_velocity[1] != 0.0f
		|| snapshot->player_velocity[2] != 0.0f);
	if (have_simvel)
	{
		VectorCopy(snapshot->player_velocity, qnn_runtime.emit_velocity);
	}
	else if (qnn_runtime.has_prev)
	{
		VectorCopy(qnn_runtime.prev_velocity, qnn_runtime.emit_velocity);
	}
	else
	{
		qnn_runtime.emit_velocity[0] = 0.0f;
		qnn_runtime.emit_velocity[1] = 0.0f;
		qnn_runtime.emit_velocity[2] = 0.0f;
	}
	qnn_runtime.emit_grounded = snapshot->grounded;
	qnn_runtime.emit_waterlevel = snapshot->waterlevel;
	qnn_runtime.emit_weapon_id = snapshot->weapon_id;
	qnn_runtime.native_frame_count = 0;
	qnn_runtime.native_fire_this_window = false;
	/* Snapshot mover positions at emission anchor. */
	for (m = 0; m < qnn_runtime.mover_count; m++)
	{
		entity_t *me = &cl_entities[qnn_runtime.mover_entity_nums[m]];
		VectorCopy(me->origin, qnn_runtime.mover_emit_origins[m]);
	}
	qnn_runtime.has_emit_anchor = true;
}

static void QNN_RuntimeReset(void)
{
	const char *dump_path;

	memset(&qnn_runtime, 0, sizeof(qnn_runtime));
	qnn_runtime.fixed_tick_hz = 20;  /* default emit rate; overridden by hello.tick_hz */
	qnn_runtime.fixed_dt = 1.0f / 20.0f;
	qnn_runtime.store_dump = NULL;

	dump_path = getenv("QNN_STORE_DUMP");
	if (dump_path != NULL && dump_path[0] != '\0')
	{
		qnn_runtime.store_dump = fopen(dump_path, "w");
		if (qnn_runtime.store_dump != NULL)
			fprintf(stderr, "[qw-demo] store dump: %s\n", dump_path);
		else
			fprintf(stderr, "[qw-demo] store dump: failed to open %s\n", dump_path);
	}
}

/* Probe native recording tick rate by counting server messages received
 * over a short window.  Informational only — engine tick is driven by
 * qnn_runtime.fixed_tick_hz from hello.tick_hz (qnn_tick_hz cvar gates
 * Host_Frame in the centralized tick path).  QW's cl.time advances every
 * Host_Frame (not per-message like NQ's cl.mtime[0]), so we key off
 * cls.netchan.incoming_sequence which increments per parsed message. */
#define QNN_DEMO_DETECT_PROBE_DT 0.001f
#define QNN_DEMO_DETECT_MAX_FRAMES 2048
#define QNN_DEMO_DETECT_SAMPLES    8

static void QNN_DetectNativeTickHz(void)
{
	int start_seq;
	double start_time;
	double end_time;
	int end_seq;
	int frame;
	float native_dt;
	int detected_hz;
	int samples;

	/* Pump until the first new server message arrives, so start_time
	 * anchors to a real message boundary rather than mid-frame. */
	start_seq = cls.netchan.incoming_sequence;
	for (frame = 0; frame < QNN_DEMO_DETECT_MAX_FRAMES; ++frame)
	{
		Host_Frame(QNN_DEMO_DETECT_PROBE_DT);
		if (!cls.demoplayback || cls.state == ca_disconnected)
			return;
		if (cls.netchan.incoming_sequence != start_seq)
		{
			start_seq = cls.netchan.incoming_sequence;
			break;
		}
	}
	start_time = cl.time;

	/* Collect QNN_DEMO_DETECT_SAMPLES additional messages. */
	samples = 0;
	end_seq = start_seq;
	for (frame = 0; frame < QNN_DEMO_DETECT_MAX_FRAMES; ++frame)
	{
		Host_Frame(QNN_DEMO_DETECT_PROBE_DT);
		if (!cls.demoplayback || cls.state == ca_disconnected)
			return;
		if (cls.netchan.incoming_sequence != end_seq)
		{
			samples += cls.netchan.incoming_sequence - end_seq;
			end_seq = cls.netchan.incoming_sequence;
			if (samples >= QNN_DEMO_DETECT_SAMPLES)
				break;
		}
	}
	if (samples < 1)
		return;

	end_time = cl.time;
	if (end_time <= start_time)
		return;

	native_dt = (float)((end_time - start_time) / (double)samples);
	if (native_dt <= 0.001f || native_dt > 1.0f)
		return;

	detected_hz = (int)(1.0f / native_dt + 0.5f);
	if (detected_hz < 5 || detected_hz > 200)
		return;

	qnn_runtime.native_hz_detected = detected_hz;
	fprintf(stderr, "[qw-demo] detected native tick rate: %d Hz (dt=%.4fs, %d samples) — engine tick = %d Hz\n",
		detected_hz, native_dt, samples, qnn_runtime.fixed_tick_hz);
}

static void QNN_CaptureSnapshotLocal(qnn_snapshot_t *snapshot, qboolean reset_flag)
{
	QNN_SyncEngineCompat();
	/* Refresh cl_entities[] PVS visibility from this frame's packet
	 * entity list before QNN_CaptureBaseSnapshot → QNN_IOUpdate →
	 * QNN_StoreUpdate → QNN_EntityClassifyKnown reads the universe.
	 * Without this, baseline-seeded items leak through as always-PVS. */
	QNN_SyncPacketEntities();
	QNN_CaptureBaseSnapshot(snapshot);
	snapshot->done = reset_flag ? false : qnn_runtime.done;
	QNN_DrainSounds(snapshot);

	/* force_mvd_emit: scrub the QWD-only velocity signal.  The MVD
	 * parser never writes playerstate.velocity, so on a real MVD
	 * playback snapshot->player_velocity is always zero.  Under
	 * force_mvd_emit on a QWD demo, the snapshot capture path would
	 * otherwise fall through to QWD's svc_playerinfo velocity (the
	 * recorder's own velocity), which is QWD-specific signal the MVD
	 * inference path must not see.  Zero it so the rest of the
	 * pipeline operates on MVD-recoverable signals only. */
	if ((qnn_runtime.force_mvd_emit || qnn_runtime.labeler_mode) && !cls.mvdplayback)
	{
		snapshot->player_velocity[0] = 0.0f;
		snapshot->player_velocity[1] = 0.0f;
		snapshot->player_velocity[2] = 0.0f;
	}
}

static qboolean QNN_ResetWorldLocal(const char *demo_path, char *error, size_t error_size)
{
	char command[QNN_WORKER_MAX_COMMAND_TEXT];
	int frame;

	if (qnn_map_state.map_name[0] == 0)
	{
		snprintf(error, error_size, "Call hello first so the worker knows which map to load");
		return false;
	}

	QNN_ClearAction(&qnn_pending_action);
	qnn_runtime.done = false;
	qnn_runtime.has_reset = false;
	qnn_runtime.mover_count = 0;
	qnn_runtime.player_count = 0;
	qnn_runtime.push_count = 0;
	qnn_sound_count = 0;
	QNN_TickEmitReset(&qnn_runtime.tick_emit);
	QNN_MvdCollectReset((uintptr_t)qnn_runtime.demo_path);
	QNN_LabelerCollectReset();
	QNN_QwdCollectReset();
	QNN_ResetPingEstimator();
	cls.demonum = -1;
	cls.timedemo = false;

	/* Clear per-demo entity / event / action state up front so that a
	 * mid-signon failure below can't leave stale qnn_store entries or
	 * mover/player indices visible to the next demo on this worker.
	 * The success path below re-runs QNN_IOInit to rebuild baselines
	 * from the newly-loaded demo. */
	QNN_IOInit(&qnn_map_state);

	CL_Disconnect();
	cls.state = ca_disconnected;

	/* Nuke any residual stufftext from the previous demo or
	 * Host_Init.  svc_stufftext messages in demos (cvar sets,
	 * disconnect, map loads) accumulate in cmd_text and would
	 * otherwise run before our playdemo, corrupting state. */
	{
		extern sizebuf_t cmd_text;
		SZ_Clear(&cmd_text);
	}

	snprintf(command, sizeof(command), "playdemo \"%s\"\n", demo_path);
	Cbuf_AddText(command);
	Cbuf_Execute();

	/* Pump frames until demo is loaded and active.  A working demo
	 * reaches ca_active within ~100 frames; if we haven't after 2048
	 * something is wrong (missing BSP, corrupt demo, etc.). */
	for (frame = 0; frame < 2048; ++frame)
	{
		Host_Frame(qnn_runtime.fixed_dt);
		if (QNN_ClientReady())
			break;
		if (frame > 0 && !cls.demoplayback && cls.state == ca_disconnected)
			break;
		/* Fail fast on missing BSP: QW parses the modellist early in
		 * signon, so cl.model_name[1] is set within a few frames. If
		 * that's set but cl.worldmodel is still NULL 256 frames later,
		 * Mod_ForName couldn't find the map file — no point pumping
		 * another 1792 frames waiting for ca_active. */
		if (frame >= 256 && cl.worldmodel == NULL && cl.model_name[1][0] != '\0')
		{
			fprintf(stderr, "[qw-demo] missing BSP: %s (worldmodel not loaded after %d frames)\n",
				cl.model_name[1], frame);
			snprintf(error, error_size, "Missing BSP %s for demo %s", cl.model_name[1], demo_path);
			return false;
		}
	}
	if (!QNN_ClientReady())
	{
		fprintf(stderr, "[qw-demo] playdemo failed: demoplayback=%d state=%d\n",
			cls.demoplayback, cls.state);
		if (!cls.demoplayback)
			snprintf(error, error_size,
				"demo_preamble_incompatible: %s (demoplayback ended during signon)",
				demo_path);
		else
			snprintf(error, error_size,
				"signon_timeout: %s (no ca_active after 2048 frames)",
				demo_path);
		return false;
	}

	/* Sync NQ compat state and baselines */
	QNN_SyncEngineCompat();
	QNN_SyncBaselines();

	/* Detect the demo's native recording rate (QWD: 10–77 Hz, MVD: ~77 Hz).
	 * If hello asked for tick_hz=0 ("emit at native"), resolve the
	 * sentinel to the per-demo detected rate now; otherwise the
	 * detection is informational only and fixed_tick_hz keeps the
	 * hello-requested value. */
	QNN_DetectNativeTickHz();
	if (qnn_runtime.requested_tick_hz == 0
		&& qnn_runtime.native_hz_detected > 0)
	{
		qnn_runtime.fixed_tick_hz = qnn_runtime.native_hz_detected;
		qnn_runtime.fixed_dt = 1.0f / (float)qnn_runtime.native_hz_detected;
		Cvar_SetValue("qnn_tick_hz",
			(float)qnn_runtime.native_hz_detected);
	}

	/* Detect actual map from worldmodel */
	if (cl.worldmodel != NULL && cl.worldmodel->name[0] != '\0')
	{
		char demo_map[QNN_MAX_MAP_ID];
		const char *bsp_name = cl.worldmodel->name;
		const char *slash;
		const char *dot;
		size_t len;

		slash = strrchr(bsp_name, '/');
		if (slash != NULL)
			bsp_name = slash + 1;
		dot = strrchr(bsp_name, '.');
		len = dot ? (size_t)(dot - bsp_name) : strlen(bsp_name);
		if (len >= sizeof(demo_map))
			len = sizeof(demo_map) - 1;
		memcpy(demo_map, bsp_name, len);
		demo_map[len] = '\0';

		if (strcasecmp(demo_map, qnn_map_state.map_name) != 0)
		{
			char map_error[256];
			if (!QNN_PrepareMap(demo_map, map_error, sizeof(map_error)))
				fprintf(stderr, "[qw-demo] map rebuild for %s failed: %s\n", demo_map, map_error);
		}
	}

	qnn_runtime.tick = 0;
	qnn_runtime.steps = 0;
	qnn_runtime.has_reset = true;
	qnn_runtime.done = false;
	QNN_IOInit(&qnn_map_state);

	if (getenv("QNN_DUMP_TEAM") != NULL)
	{
		int slot;
		const char *teamplay = Info_ValueForKey(cl.serverinfo, "teamplay");
		const char *deathmatch = Info_ValueForKey(cl.serverinfo, "deathmatch");
		fprintf(stderr, "[team-dump] demo=%s\n", demo_path);
		fprintf(stderr, "[team-dump] cl.playernum=%d teamplay=\"%s\" deathmatch=\"%s\"\n",
			cl.playernum, teamplay, deathmatch);
		for (slot = 0; slot < MAX_CLIENTS; ++slot)
		{
			player_info_t *p = &cl.players[slot];
			const char *team;
			const char *topcolor;
			const char *bottomcolor;
			if (p->name[0] == '\0' && p->userinfo[0] == '\0')
				continue;
			team = Info_ValueForKey(p->userinfo, "team");
			topcolor = Info_ValueForKey(p->userinfo, "topcolor");
			bottomcolor = Info_ValueForKey(p->userinfo, "bottomcolor");
			{
				char team_hex[64];
				size_t i, n = strlen(team);
				if (n > sizeof(team_hex) / 3 - 1)
					n = sizeof(team_hex) / 3 - 1;
				team_hex[0] = '\0';
				for (i = 0; i < n; ++i)
					snprintf(team_hex + i * 3, 4, "%02x ", (unsigned char)team[i]);
				fprintf(stderr,
					"[team-dump] slot=%2d name=\"%s\" spec=%d team_hex=[%s] top=\"%s\" bot=\"%s\"%s\n",
					slot, p->name, p->spectator, team_hex, topcolor, bottomcolor,
					(slot == cl.playernum) ? " <-- recorder" : "");
			}
		}
		fflush(stderr);
	}

	return true;
}

static void QNN_WriteHelloResponse(void)
{
	fprintf(stdout, "{\"capabilities\":[\"demo_playback\",\"qw_demo\",\"mvd_demo\",\"navmesh_query_v1\",\"obs_buffer_collect_v1\"],\"map_id\":");
	QNN_WriteJsonString(stdout, qnn_map_state.requested_map_id);
	fprintf(stdout, ",\"ok\":true,\"protocol_version\":");
	QNN_WriteJsonString(stdout, QNN_WORKER_PROTOCOL);
	fprintf(stdout, ",\"server\":");
	QNN_WriteJsonString(stdout, QNN_WORKER_SERVER_NAME);
	fprintf(stdout, ",\"tick_hz\":%d,\"worker_build\":{\"basedir\":", qnn_runtime.fixed_tick_hz);
	QNN_WriteJsonString(stdout, basedir);
	fprintf(stdout, ",\"upstream_commit\":");
	QNN_WriteJsonString(stdout, QNN_WORKER_UPSTREAM_COMMIT);
	fprintf(stdout, "}}\n");
	fflush(stdout);
}

/* QNN_OpIs — shared in common/qnn_collect_helpers.c. */

static int QNN_HandleHello(const char *line)
{
	char map_id[QNN_MAX_MAP_ID];
	char error[256];

	memset(map_id, 0, sizeof(map_id));
	memset(error, 0, sizeof(error));
	if (!QNN_JsonExtractString(line, "\"map_id\"", map_id, sizeof(map_id)))
		snprintf(map_id, sizeof(map_id), "dm3");

	{
		/* hello.tick_hz = 0 → emit at the demo's native recording rate.
		 * We can't know that rate until DetectNativeTickHz runs (post-
		 * signon), so park fixed_tick_hz at the sentinel 0 here and use
		 * a safe 77 Hz fixed_dt for signon-phase Host_Frame calls.
		 * QNN_HandleCollect resolves the sentinel against
		 * native_hz_detected immediately after signon. */
		int tick_hz = QNN_JsonExtractInt(line, "\"tick_hz\"", 20);
		if (tick_hz < 0) tick_hz = 0;
		qnn_runtime.requested_tick_hz = tick_hz;
		qnn_runtime.fixed_tick_hz = tick_hz;
		qnn_runtime.fixed_dt = (tick_hz > 0)
			? 1.0f / (float)tick_hz
			: 1.0f / 77.0f;
		Cvar_SetValue("qnn_tick_hz",
			(float)(tick_hz > 0 ? tick_hz : 77));
	}

	if (!QNN_PrepareMap(map_id, error, sizeof(error)))
	{
		QNN_WriteError(error);
		return 0;
	}

	QNN_WriteHelloResponse();
	return 0;
}

static int QNN_HandleCollect(const char *line)
{
	qnn_action_t native_action;
	qnn_snapshot_t snapshot;
	char demo_path[MAX_OSPATH];
	char error[256];
	int mvd_player_num;

	int play_start, play_end;

	memset(demo_path, 0, sizeof(demo_path));
	memset(error, 0, sizeof(error));
	mvd_player_num = QNN_JsonExtractInt(line, "\"player_num\"", -1);
	play_start = QNN_JsonExtractInt(line, "\"play_start\"", 0);
	play_end = QNN_JsonExtractInt(line, "\"play_end\"", 999999999);
	qnn_runtime.force_mvd_emit = QNN_JsonExtractInt(line, "\"force_mvd_emit\"", 0) != 0;
	qnn_runtime.labeler_mode   = QNN_JsonExtractInt(line, "\"labeler_mode\"",   0) != 0;
	if (!QNN_JsonExtractString(line, "\"demo_path\"", demo_path, sizeof(demo_path)))
	{
		QNN_WriteError("reset options must include demo_path");
		return 0;
	}
	Q_strncpy(qnn_runtime.demo_path, demo_path, sizeof(qnn_runtime.demo_path) - 1);
	qnn_runtime.demo_path[sizeof(qnn_runtime.demo_path) - 1] = '\0';
	QNN_FaultSetContext(demo_path);
	if (!QNN_ResetWorldLocal(demo_path, error, sizeof(error)))
	{
		QNN_WriteError(error);
		QNN_FaultSetContext(NULL);
		return 0;
	}

	/* QC VM init must happen AFTER QNN_ResetWorldLocal: the world reset
	 * resets the QW client's hunk (Host_ClearMemory), which would wipe
	 * any memory PR_LoadProgs had allocated for progs/pr_functions/
	 * pr_strings/etc.  Initializing here puts the QC bytecode at the
	 * top of the hunk where it stays valid for the duration of demo
	 * playback.  QC VM is the canonical source of truth for the labeler's
	 * op_input (fire / jump operativeness) — if it fails to load,
	 * the worker has no principled sanitization, so we hard-fail. */
	if (!QNN_ProgsInit())
	{
		QNN_WriteError("qnn_progs: QC VM init failed (qwprogs.dat missing or "
			"version mismatch).  Labeler-mode collect requires QC VM for "
			"op_input sanitization.");
		QNN_FaultSetContext(NULL);
		return 0;
	}

	/* cl_nopred: always run prediction.
	 *
	 * Prediction is left on regardless of mode because CL_PredictMove
	 * is also what keeps the engine's module-level `waterlevel` and the
	 * playerstate `onground` field current in QWD playback — turning
	 * it off collapses snapshot->grounded/waterlevel to a single regime
	 * (100% ground) and breaks the labeler's movement_id feature.
	 *
	 * QWD leakage from pmove is suppressed at the source: under
	 * force_mvd_emit / labeler_mode, qnn_self.c QNN_CaptureBaseSnapshot
	 * routes origin/velocity through the server playerstate
	 * (ps->origin / ps->velocity) instead of the pmove-driven
	 * cl.simorg / cl.simvel, and QNN_CaptureSnapshotLocal then zeros
	 * player_velocity to match real MVD (MVD parser never writes
	 * playerstate.velocity). */
	Cvar_Set("cl_nopred", "0");

	/* MVD: select tracked player and initialize physics inference.
	 * Tick rate already detected in QNN_ResetWorldLocal via
	 * QNN_DetectNativeTickHz (~77 Hz on MVDSV, varies elsewhere). */
	if (cls.mvdplayback)
	{
		int p;

		/* Select player: use requested player_num or auto-select */
		if (mvd_player_num >= 0 && mvd_player_num < MAX_CLIENTS
			&& cl.players[mvd_player_num].name[0] != '\0')
		{
			cl.playernum = mvd_player_num;
		}
		else
		{
			for (p = 0; p < MAX_CLIENTS; p++)
			{
				if (cl.players[p].name[0] != '\0'
					&& !cl.players[p].spectator)
				{
					cl.playernum = p;
					break;
				}
			}
		}
		fprintf(stderr, "[qw-demo] MVD tracking player %d: %s\n",
			cl.playernum, cl.players[cl.playernum].name);
	}

	/* Initialize BSP-clipped physics for any path that will call into
	 * PlayerMove() during this demo: MVD movement inference, QWD MVD-
	 * inference (force_mvd_emit), and the QWD labeler's per-cmd pmove
	 * jump driver.  Without this, pmove.physents[0].model points at the
	 * previous demo's freed worldmodel (or NULL on the first demo) and
	 * the next trace SEGVs. */
	if (cls.mvdplayback || qnn_runtime.force_mvd_emit
		|| qnn_runtime.labeler_mode)
		QNN_PhysInit();

	/* Engine tick = emit tick.  fixed_dt was set from hello.tick_hz and
	 * matches qnn_tick_hz cvar; QNN_TickGate in cl_main.c lets every
	 * Host_Frame(fixed_dt) call advance.  No resample aggregation. */

	/* play_start / play_end arrive as native-frame indices from the
	 * classifier.  qnn_runtime.tick increments per emit at fixed_tick_hz,
	 * so we convert once now using the engine-detected native rate.
	 * If detection failed (native_hz_detected==0), fall back to the
	 * upstream defaults: 77 Hz QW, 72 Hz NQ. */
	{
		int native_hz = qnn_runtime.native_hz_detected > 0
			? qnn_runtime.native_hz_detected
			: 77;
		if (play_start > 0)
			play_start = (int)(((long long)play_start * qnn_runtime.fixed_tick_hz) / native_hz);
		if (play_end < 999999999)
			play_end = (int)(((long long)play_end * qnn_runtime.fixed_tick_hz) / native_hz);
		fprintf(stderr, "[qw-demo] play gate (native→emit @ %d Hz / %d Hz): play_start=%d play_end=%d\n",
			native_hz, qnn_runtime.fixed_tick_hz, play_start, play_end);
	}

	{
		int emit_hz = qnn_runtime.fixed_tick_hz;

		QNN_CaptureSnapshotLocal(&snapshot, true);
		QNN_SavePrev(&snapshot, 0.0f);
		QNN_SaveEmitAnchor(&snapshot);
		QNN_IOUpdate(&snapshot, qnn_runtime.fixed_dt, true);
		QNN_BuildAllRefs();

		{
			qboolean emitting = false;

		QNN_WatchdogBegin(10);
		while (!qnn_runtime.done)
		{
			qnn_runtime.cmd_seq_window_start = cls.netchan.outgoing_sequence;
			qnn_runtime.emit_start_native = (float)cl.time;
			Host_Frame(qnn_runtime.fixed_dt);
			QNN_WatchdogTick();
			qnn_runtime.tick += 1;
			qnn_runtime.steps += 1;

			if (!cls.demoplayback || cls.state == ca_disconnected)
				qnn_runtime.done = true;

			/* Frame-gated emission: play_start..play_end from the
			 * offline analyzer.  Everything outside is skipped. */
			if (qnn_runtime.tick > play_end)
			{
				snapshot.done = true;
				qnn_runtime.done = true;
			}

			QNN_CaptureSnapshotLocal(&snapshot, false);

			if (!emitting && qnn_runtime.tick >= play_start)
			{
				emitting = true;
				QNN_IOUpdate(&snapshot, qnn_runtime.fixed_dt, true);
				QNN_SaveEmitAnchor(&snapshot);
				fprintf(stderr, "[qw-demo] emitting from tick %d (play_start=%d play_end=%d)\n",
					qnn_runtime.tick, play_start, play_end);
				QNN_SavePrev(&snapshot, qnn_runtime.fixed_dt);
				continue;
			}

			if (!emitting && !qnn_runtime.done)
			{
				QNN_SavePrev(&snapshot, qnn_runtime.fixed_dt);
				continue;
			}

			QNN_IOUpdate(&snapshot, qnn_runtime.fixed_dt, false);

			if (qnn_runtime.store_dump != NULL)
			{
				QNN_StoreDumpSounds(qnn_runtime.store_dump, qnn_runtime.tick, &snapshot);
				QNN_StoreDumpTick(qnn_runtime.store_dump, qnn_runtime.tick, (float)cl.mtime[0]);
			}

			/* Buffer per-native-frame mover and other-player positions
			 * so the emission-time physics inference can set up the
			 * correct BSP collision state for the 9 candidates. */
			if ((cls.mvdplayback || qnn_runtime.force_mvd_emit) && !snapshot.done)
			{
				int nf = qnn_runtime.native_frame_count;
				if (nf < QNN_MAX_NATIVE_FRAMES)
				{
					int m;
					for (m = 0; m < qnn_runtime.mover_count; m++)
					{
						entity_t *me = &cl_entities[qnn_runtime.mover_entity_nums[m]];
						VectorCopy(me->origin, qnn_runtime.mover_origins[nf][m]);
					}
					for (m = 0; m < qnn_runtime.player_count; m++)
					{
						int entnum = qnn_runtime.player_entity_nums[m];
						VectorCopy(qnn_store[entnum].origin,
							qnn_runtime.player_origins[nf][m]);
					}
					qnn_runtime.native_frame_count = nf + 1;
				}
			}

			/* Extract per-frame action (MVD path only).
			 *
			 * MVD branch carries a real side effect:
			 * QNN_MvdInferNativeAction sets
			 * qnn_runtime.native_fire_this_window for the back-shift
			 * fire emit downstream.
			 *
			 * QWD branch was a dead call: native_action is
			 * write-only across this function, so the only effect of
			 * calling QwdExtractAction here was advancing
			 * qnn_progs_attack_finished a second time within the same
			 * tick — QwdInferEmitAction (line below) internally calls
			 * QwdExtractAction once per tick already, and the per-cmd
			 * loop's QNN_ProgsEvalAttack on the second call saw the
			 * just-set future attack_finished and rejected every
			 * fire, leaving qwd_state.last_op_fire = 0 in the stash
			 * QwdPackOpInput reads. Result: op_input bit 3 never set
			 * across the BC QWD corpus. Same failure mode commit
			 * 4c7c9b4d fixed for the labeler path. */
			if (!snapshot.done)
			{
				if (cls.mvdplayback || qnn_runtime.force_mvd_emit)
					QNN_MvdInferNativeAction(&native_action,
						&snapshot);
			}

			/* Emit-time action label.  QWD path is a pure usercmd-byte
			 * decoder (action.weapon written canonically inside
			 * QNN_QwdInferEmitAction); MVD path runs inference. */
			if (!snapshot.done)
			{
				if (cls.mvdplayback || qnn_runtime.force_mvd_emit)
				{
					float phys_dt;
					QNN_MvdInferEmitAction(
						&snapshot.action_label,
						&snapshot);
					phys_dt = qnn_runtime.native_frame_count
						* qnn_runtime.fixed_dt;
					if (phys_dt > 0.0f)
					{
						QNN_MvdInferEmitMove(
							&snapshot.action_label,
							&snapshot, phys_dt);
						qnn_runtime.prev_move[0] = snapshot.action_label.move[0];
						qnn_runtime.prev_move[1] = snapshot.action_label.move[1];
						qnn_runtime.prev_move[2] = snapshot.action_label.move[2];
					}
					else
					{
						snapshot.action_label.move[0] = qnn_runtime.prev_move[0];
						snapshot.action_label.move[1] = qnn_runtime.prev_move[1];
						snapshot.action_label.move[2] = qnn_runtime.prev_move[2];
					}
				}
				else
				{
					QNN_QwdInferEmitAction(
						&snapshot.action_label,
						&snapshot);
				}
			}
			else
				QNN_ClearAction(&snapshot.action_label);

			/* Labeler-mode LOBS emit: bypass the QOBS pipeline entirely
			 * (no jitter filter, no back-shift ring, no fire-hold).
			 * One LOBS frame per native tick.  Target move comes from
			 * the action label which is filled above — usercmd truth on
			 * QWD demos (the labeler's training distribution); MVD-rule
			 * inference if applied to a real MVD (no truth available). */
			if (qnn_runtime.labeler_mode)
			{
				QNN_LabelerHandleTick(&snapshot, stdout);
				if (snapshot.done)
					qnn_runtime.done = true;
				continue;
			}
			{
				FILE *emit_out;
				qnn_snapshot_t filter_snapshot;
				qboolean mvd_path =
					(cls.mvdplayback || qnn_runtime.force_mvd_emit);
				uint8_t obs_bytes[QNN_OBS_BUFFER_SIZE];
				int cur_weapon = snapshot.weapon_id;

				if (qnn_runtime.force_mvd_emit && !cls.mvdplayback)
				{
					filter_snapshot = snapshot;
					QNN_QwdInferEmitAction(&filter_snapshot.action_label,
						&snapshot);
					emit_out = QNN_EmitFilter(&filter_snapshot);
					if (snapshot.health <= 0)
					{
						snapshot.action_label.fire = 1;
						snapshot.action_label.move[0] = 0.0f;
						snapshot.action_label.move[1] = 0.0f;
						snapshot.action_label.move[2] = 0.0f;
					}
				}
				else
				{
					emit_out = QNN_EmitFilter(&snapshot);
				}

				/* QWD path is a pure cmd-byte decoder — action.weapon
				 * is already the canonical label, no rewriting needed.
				 * Only the MVD path runs back-shift inference (weapon
				 * via ping-shift + pickup gate, fire/jump per-event). */
				QNN_PackSnapshotObs(&snapshot, obs_bytes);

				/* Maintain per-demo running median of svc_updateping
				 * values (used by QNN_PressBackShiftFrames on the MVD
				 * path as a garbage-input fallback). */
				QNN_ObservePings();

				if (mvd_path)
				{
					int prev_weapon = 0;
					qboolean has_prev_weapon =
						QNN_MvdBackShiftPrevWeapon(&prev_weapon);
					if (has_prev_weapon
						&& prev_weapon != cur_weapon
						&& cur_weapon > 0)
					{
						int shift;
						/* Pickup gate: if the new weapon's IT_ bit
						 * flipped 0→1 this frame, the transition is the
						 * server's weapon_touch auto-switch (items|=new
						 * and self.weapon=new in one QC call).  Impulse
						 * handlers can't fire on a bit that wasn't
						 * already on, so a player-intent switch can
						 * only land ≥1 frame later.  Leave the label
						 * at the server-observed frame. */
						int it_bit = QNN_ItemFlagFromImpulse(cur_weapon);
						int items_now = cl.stats[STAT_ITEMS];
						int prev_items = 0;
						qboolean has_prev_items =
							QNN_MvdBackShiftPrevStatItems(&prev_items);
						qboolean is_pickup =
							has_prev_items
							&& it_bit
							&& (items_now & it_bit)
							&& !(prev_items & it_bit);
						if (is_pickup)
							shift = 0;
						else
							shift = QNN_PressBackShiftFrames(
								cl.playernum, emit_hz);
						QNN_MvdBackShiftOnWeaponChange(
							cur_weapon, prev_weapon, shift);

						/* Break fire carryover across weapon transitions.
						 * Clear the old weapon's chain state so a later
						 * same-weapon shot isn't false-linked through a
						 * different-weapon interval, and clear pending
						 * hold spillover so post-switch fire=1 frames are
						 * not inherited from the pre-switch weapon. */
						QNN_MvdResetFireChain(prev_weapon);
					}
				}

				QNN_MvdBackShiftPush(
					&qnn_runtime.tick_emit, emit_out,
					obs_bytes, &snapshot.action_label,
					snapshot.done,
					qnn_runtime.tick, qnn_runtime.steps,
					emit_hz, false, snapshot.grounded,
					cur_weapon,
					cl.stats[STAT_ITEMS]);

				if (mvd_path)
				{
					/* Fire + jump: per-event back-shift via native_time.
					 * Both use the same ping-RTT correction: sound
					 * arrives at the recording client one full RTT
					 * after the button press.
					 *
					 * No bias correction applied: validation against
					 * direct demo-byte press/sound timestamps on the
					 * fire_lat2 138-demo set shows the engine is already
					 * close to the right operating point with svc_update
					 * ping.  Median residual is −13 ms but the
					 * distribution is heavy-positive-tailed (mean
					 * −1.4 ms), so subtracting a full native period
					 * shifts the bulk too far and net exact-frame
					 * recall drops (76.58 % → 59.06 %).  Reach the
					 * remaining ~6 pp gap to ceiling via per-press
					 * ping (QNN_LatencySeconds on QWD, no alternative
					 * available on MVD playback) instead. */
					if (snapshot.health > 0)
					{
						/* Single ping authority — same source
						 * (median-fallback, outlier-rejected) as
						 * the weapon/move bulk shift via
						 * QNN_PressBackShiftFrames. */
						float ping_sec = QNN_PressPingSec(cl.playernum);
						QNN_MvdBackShiftWriteFireEvents(&snapshot,
							ping_sec,
							qnn_runtime.emit_start_native);
						QNN_MvdBackShiftWriteJumpEvents(&snapshot,
							ping_sec,
							qnn_runtime.emit_start_native);
					}

					/* Move: continuous label.  Today's velocity-sign
					 * reflects the keyboard press from `shift` emit
					 * frames ago, so write today's move to the back-
					 * shifted slot. */
					{
						int shift = QNN_PressBackShiftFrames(
							cl.playernum, emit_hz);
						QNN_MvdBackShiftWriteMoveXY(
							snapshot.action_label.move, shift);
					}
				}
			}
			if (!snapshot.done)
				QNN_SaveEmitAnchor(&snapshot);

			QNN_SavePrev(&snapshot, qnn_runtime.fixed_dt);
		}
		QNN_WatchdogEnd();

		QNN_MvdBackShiftFlushAll(&qnn_runtime.tick_emit);
		QNN_FlushTickEmit(&qnn_runtime.tick_emit);

		if (!qnn_runtime.tick_emit.has_prev_emitted)
		{
			/* Demo ended without emitting any tick — reached
			 * play_end before play_start (degenerate range),
			 * aborted during signon, or replay produced zero
			 * usable frames. Emit a done-tick so the reader
			 * doesn't block waiting for FLAG_DONE. */
			snapshot.done = true;
			QNN_WriteObsTick(&qnn_runtime.tick_emit, stdout,
				&snapshot, qnn_runtime.tick,
				qnn_runtime.steps, emit_hz, true);
		}
		}
	}
	fflush(stdout);
	if (qnn_runtime.store_dump != NULL)
	{
		fflush(qnn_runtime.store_dump);
		fclose(qnn_runtime.store_dump);
		qnn_runtime.store_dump = NULL;
	}
	QNN_FaultSetContext(NULL);
	return 0;
}

int main(int argc, char **argv)
{
	quakeparms_t parms;
	char line[QNN_WORKER_MAX_LINE];

	QNN_FaultInit("qw_demo_worker");
	QNN_ResolveBasedir(qnn_basedir_storage, sizeof(qnn_basedir_storage));
	QNN_RuntimeReset();
	QNN_ClearAction(&qnn_pending_action);
	memset(&parms, 0, sizeof(parms));
	COM_InitArgv(argc, argv);
	parms.argc = com_argc;
	parms.argv = com_argv;
	parms.memsize = 128 * 1024 * 1024;
	parms.membase = malloc(parms.memsize);
	parms.basedir = basedir;
	Host_Init(&parms);
	QNN_TickRegister();

	/* QW's Host_Init runs quake.rc which may connect somewhere.
	 * Disconnect and reset state for worker mode. */
	Cbuf_Execute();
	cls.demonum = -1;
	CL_Disconnect();
	cls.state = ca_disconnected;

	/* Optional: load qwprogs.dat into the server VM and run a smoke
	 * test of the QC VM predicates.  Per-demo QNN_ProgsInit fires from
	 * the "reset" handler; this argv switch lets bring-up validation
	 * run without dispatching a real demo. */
	if (COM_CheckParm("-sanitize-smoke"))
	{
		if (QNN_ProgsInit())
			QNN_ProgsSmokeTest();
	}

	while (fgets(line, sizeof(line), stdin) != NULL)
	{
		/* Match the "op" key precisely — substring search on the raw
		 * line collides with demo filenames that happen to contain
		 * the keyword (e.g. _vs_hello_kitty_).  Looking for the
		 * literal "op":"<value>" pattern (with or without a space)
		 * keeps us schema-tolerant without pulling in a JSON parser. */
		if (QNN_OpIs(line, "hello"))
		{
			QNN_HandleHello(line);
			continue;
		}
		if (QNN_OpIs(line, "nav_query"))
		{
			QNN_HandleNavQuery(line);
			continue;
		}
		if (QNN_OpIs(line, "collect"))
		{
			QNN_HandleCollect(line);
			continue;
		}
		if (QNN_OpIs(line, "shutdown"))
		{
			fprintf(stdout, "{\"ok\":true}\n");
			fflush(stdout);
			QNN_FreeMapState(&qnn_map_state);
			Host_Shutdown();
			return 0;
		}
	}

	QNN_FreeMapState(&qnn_map_state);
	Host_Shutdown();
	return 0;
}
