/*
 * qnn_collect_main.c (qw) — Main loop for the QW demo worker.
 *
 * QW equivalent of nq/qnn_collect_main.c.  Handles two demo formats:
 *
 *   QWD (client-side): dem_cmd messages contain usercmd_t with the
 *     player's exact inputs — ground truth labels.
 *
 *   MVD (server-side): No usercmd_t.  All player state is visible.
 *     Actions are inferred from position/angle/state deltas using the
 *     same approach as the NQ worker: 9-candidate BSP physics for
 *     movement (via QW pmove), sound/state cues for attack/jump.
 *
 * Client state sync via QNN_SyncEngineCompat() each frame.
 * Output format is identical to the NQ worker (QOBS framed binary)
 * so bc_collect.py can consume it directly.
 */

#include "qnn.h"
#include "qnn_collect_helpers.h"
#include "qnn_weapon.h"
#include "qnn_mvd_collect.h"
#include "qnn_qwd_collect.h"
#include "qnn_fault.h"
#include "qnn_io.h"
#include "qnn_store.h"
#include "qnn_metrics.h"
#include "qnn_watchdog.h"
#include "qnn_tick.h"

#include <math.h>
#include <stdlib.h>
#include <string.h>

#define QNN_WORKER_SERVER_NAME "qw-demo-worker"

/* Engine-compat sync — defined in qnn_engine_compat.c, generated by the
 * QW build script.  Mirrors the QW client's playernum/time/scoreboard
 * into the NQ-flavor fields the shared worker code reads. */
extern void QNN_SyncEngineCompat(void);
extern void QNN_SyncBaselines(void);
/* Per-frame entity visibility refresh — clears cl_entities[].model
 * for non-PVS slots so the shared QNN_EntityClassifyKnown walk sees
 * the same universe a normal NQ client would.  See qnn_engine_compat.c. */
extern void QNN_SyncPacketEntities(void);

#define QNN_TELEPORT_DIST_SQ (400.0f * 400.0f)

static qboolean QNN_ClientReady(void)
{
	/* QW uses ca_active instead of ca_connected + SIGNONS */
	return (cls.demoplayback
		&& cls.state == ca_active
		&& cl.worldmodel != NULL
		&& cl.playernum >= 0
		&& cl.playernum < MAX_CLIENTS) ? true : false;
}

/* Build mover/push/player refs into the runtime via shared scanners
 * in common/qnn_collect_helpers.c. */
static void QNN_BuildAllRefs(void)
{
	qnn_runtime.mover_count = QNN_BuildMoverRefs(
		qnn_runtime.mover_entity_nums,
		qnn_runtime.mover_model_indices,
		QNN_MAX_PHYS_MOVERS);
	qnn_runtime.push_count = QNN_BuildPushRefs(
		qnn_runtime.push_model_indices,
		qnn_runtime.push_velocities,
		QNN_MAX_PUSH_TRIGGERS);
	qnn_runtime.player_count = QNN_BuildPlayerRefs(
		cl.playernum + 1,	/* QW: tracked player's entity */
		qnn_runtime.player_entity_nums,
		QNN_MAX_PHYS_PLAYERS);
	if (qnn_runtime.mover_count > 0)
		fprintf(stderr, "[qw-demo] tracking %d movers for physics baseline\n",
			qnn_runtime.mover_count);
	if (qnn_runtime.push_count > 0)
		fprintf(stderr, "[qw-demo] tracking %d push triggers for velocity subtraction\n",
			qnn_runtime.push_count);
	if (qnn_runtime.player_count > 0)
		fprintf(stderr, "[qw-demo] tracking %d other players for body-block collision\n",
			qnn_runtime.player_count);
}

/* ── Action extraction from QWD usercmd_t ─────────────────────────
 *
 * QWD demos carry dem_cmd messages with usercmd_t (forwardmove, sidemove,
 * upmove, buttons, impulse, angles).  The cmd-window walker that
 * aggregates these into a single emit-rate action label lives in
 * src/engine/qw/qnn_qwd_collect.c.  See QNN_QwdExtractAction /
 * QNN_QwdBuildActionLabel.
 */


/* ── MVD action inference ─────────────────────────────────────────
 *
 * Used on real MVD demos (cls.mvdplayback) or `force_mvd_emit` QWDs —
 * paths where no usercmd_t ground truth is available.  Lives in
 * src/engine/common/qnn_mvd_collect.c.  See QNN_MvdInferNativeAction /
 * QNN_MvdInferEmitAction / QNN_MvdInferEmitMove.
 */

/* ── Emit one tick ─────────────────────────────────────────────── */

/* QNN_EmitTick, QNN_JitterFilter, QNN_ActionIsFrozen, QNN_WriteObsTick,
 * QNN_FlushTickEmit, QNN_EmitFilter, QNN_SavePrev — shared in
 * common/qnn_collect_helpers.c. */

static void QNN_SaveEmitAnchor(const qnn_snapshot_t *snapshot)
{
	int m;
	qboolean have_simvel;

	VectorCopy(snapshot->player_view_angles, qnn_runtime.emit_view_angles);
	VectorCopy(snapshot->player_origin, qnn_runtime.emit_origin);

	/* Prefer the client-predicted simvel captured on the snapshot over
	 * the origin-delta approximation.  QW's CL_PredictMove runs the
	 * same pmove integrator the server used, so simvel is the
	 * instantaneous velocity at the emission moment — exactly what the
	 * 9-candidate physics needs as its starting velocity.  The
	 * origin-delta fallback (prev_velocity) averages over the previous
	 * 20 ms native tick, so it's a frame-old estimate that causes
	 * candidate endpoints to drift when the player is accelerating or
	 * decelerating. */
	have_simvel = (snapshot->player_velocity[0] != 0.0f
		|| snapshot->player_velocity[1] != 0.0f
		|| snapshot->player_velocity[2] != 0.0f);
	if (have_simvel)
	{
		VectorCopy(snapshot->player_velocity, qnn_runtime.emit_velocity);
	}
	else if (qnn_runtime.has_prev)
	{
		VectorCopy(qnn_runtime.prev_velocity, qnn_runtime.emit_velocity);
	}
	else
	{
		qnn_runtime.emit_velocity[0] = 0.0f;
		qnn_runtime.emit_velocity[1] = 0.0f;
		qnn_runtime.emit_velocity[2] = 0.0f;
	}
	qnn_runtime.emit_grounded = snapshot->grounded;
	qnn_runtime.emit_waterlevel = snapshot->waterlevel;
	qnn_runtime.emit_weapon_id = snapshot->weapon_id;
	qnn_runtime.native_frame_count = 0;
	qnn_runtime.native_attack_this_window = false;
	/* Snapshot mover positions at emission anchor. */
	for (m = 0; m < qnn_runtime.mover_count; m++)
	{
		entity_t *me = &cl_entities[qnn_runtime.mover_entity_nums[m]];
		VectorCopy(me->origin, qnn_runtime.mover_emit_origins[m]);
	}
	qnn_runtime.has_emit_anchor = true;
}

/* Pack action->input_mask on MVD-path collects — same pure-feasibility
 * semantics as QNN_QwdPackInputMask, built only from MVD-observable
 * state: alive, BSP-derived grounded/waterlevel, stats ammo, held
 * weapon, and the QC VM's attack_finished (cmd-driven under
 * force_mvd_emit; shot-driven on real .mvd playback — see the
 * cooldown driver in the emit loop).  Without this, MVD collects
 * carried input_mask = 0 on every frame, and under input_mask=true
 * training the feasibility-AND-press label rewrite would zero every
 * head's labels — the corpus would train toward "never act".
 *
 * `start_of_tick_attack_finished` mirrors the QWD pre-loop semantics:
 * bit 0 means "could press attack at the START of this tick", so AND
 * with the press recovers the engine-attacked-this-tick label. */
static void QNN_MvdPackInputMask(qnn_action_t *action,
	const qnn_snapshot_t *snapshot, float start_of_tick_attack_finished)
{
	int in_water;
	int op_attack;
	int op_jump;

	if (snapshot->health <= 0)
	{
		action->input_mask = 0;
		return;
	}
	in_water = (snapshot->waterlevel >= 2);

	/* Shared feasibility probe (same core as the QWD path). Baseline is the
	 * shot-stamped start-of-tick attack_finished. */
	op_attack = QNN_EvalAttackFeasible(snapshot, start_of_tick_attack_finished);

	/* No cmd stream maintains the JUMPRELEASED carry on this path —
	 * assert released-since-last-tick so the predicate evaluates the
	 * grounded/water/alive gates (see QNN_ProgsSetJumpReleased). */
	QNN_ProgsSetJumpReleased(true);
	op_jump = QNN_ProgsEvalJump(
		QNN_RuntimeNowSeconds(),
		snapshot->health, snapshot->grounded ? 1 : 0,
		snapshot->waterlevel, /*button2=*/1);

	action->input_mask = QNN_PackInputMask(
		1,
		/*fb_act_neg=*/1, /*fb_act_pos=*/1,
		/*lr_act_neg=*/1, /*lr_act_pos=*/1,
		/*up_act_neg=*/in_water ? 1 : 0,
		/*up_act_pos=*/in_water ? 1 : 0,
		op_jump, op_attack);
}

static void QNN_RuntimeReset(void)
{
	const char *dump_path;

	memset(&qnn_runtime, 0, sizeof(qnn_runtime));
	qnn_runtime.fixed_tick_hz = 20;  /* default emit rate; overridden by hello.tick_hz */
	qnn_runtime.fixed_dt = 1.0f / 20.0f;
	qnn_runtime.store_dump = NULL;

	dump_path = getenv("QNN_STORE_DUMP");
	if (dump_path != NULL && dump_path[0] != '\0')
	{
		qnn_runtime.store_dump = fopen(dump_path, "w");
		if (qnn_runtime.store_dump != NULL)
			fprintf(stderr, "[qw-demo] store dump: %s\n", dump_path);
		else
			fprintf(stderr, "[qw-demo] store dump: failed to open %s\n", dump_path);
	}

	{
		/* Per-sound capture dump (entity + native_time + name) for
		 * attack-label auditing. Opened once across demos. */
		extern FILE *qnn_sound_dump;
		const char *snd_dump = getenv("QNN_SOUND_DUMP");
		if (snd_dump != NULL && snd_dump[0] != '\0' && qnn_sound_dump == NULL)
			qnn_sound_dump = fopen(snd_dump, "w");
	}
}

/* Probe native recording tick rate by counting server messages received
 * over a short window.  Informational only — engine tick is driven by
 * qnn_runtime.fixed_tick_hz from hello.tick_hz (qnn_tick_hz cvar gates
 * Host_Frame in the centralized tick path).  QW's cl.time advances every
 * Host_Frame (not per-message like NQ's cl.mtime[0]), so we key off
 * cls.netchan.incoming_sequence which increments per parsed message. */
#define QNN_DEMO_DETECT_PROBE_DT 0.001f
#define QNN_DEMO_DETECT_MAX_FRAMES 2048
#define QNN_DEMO_DETECT_SAMPLES    8

static void QNN_DetectNativeTickHz(void)
{
	int start_seq;
	double start_time;
	double end_time;
	int end_seq;
	int frame;
	float native_dt;
	int detected_hz;
	int samples;

	/* Pump until the first new server message arrives, so start_time
	 * anchors to a real message boundary rather than mid-frame. */
	start_seq = cls.netchan.incoming_sequence;
	for (frame = 0; frame < QNN_DEMO_DETECT_MAX_FRAMES; ++frame)
	{
		Host_Frame(QNN_DEMO_DETECT_PROBE_DT);
		if (!cls.demoplayback || cls.state == ca_disconnected)
			return;
		if (cls.netchan.incoming_sequence != start_seq)
		{
			start_seq = cls.netchan.incoming_sequence;
			break;
		}
	}
	start_time = cl.time;

	/* Collect QNN_DEMO_DETECT_SAMPLES additional messages. */
	samples = 0;
	end_seq = start_seq;
	for (frame = 0; frame < QNN_DEMO_DETECT_MAX_FRAMES; ++frame)
	{
		Host_Frame(QNN_DEMO_DETECT_PROBE_DT);
		if (!cls.demoplayback || cls.state == ca_disconnected)
			return;
		if (cls.netchan.incoming_sequence != end_seq)
		{
			samples += cls.netchan.incoming_sequence - end_seq;
			end_seq = cls.netchan.incoming_sequence;
			if (samples >= QNN_DEMO_DETECT_SAMPLES)
				break;
		}
	}
	if (samples < 1)
		return;

	end_time = cl.time;
	if (end_time <= start_time)
		return;

	native_dt = (float)((end_time - start_time) / (double)samples);
	if (native_dt <= 0.001f || native_dt > 1.0f)
		return;

	detected_hz = (int)(1.0f / native_dt + 0.5f);
	if (detected_hz < 5 || detected_hz > 200)
		return;

	qnn_runtime.native_hz_detected = detected_hz;
	fprintf(stderr, "[qw-demo] detected native tick rate: %d Hz (dt=%.4fs, %d samples) — engine tick = %d Hz\n",
		detected_hz, native_dt, samples, qnn_runtime.fixed_tick_hz);
}

static void QNN_CaptureSnapshotLocal(qnn_snapshot_t *snapshot, qboolean reset_flag)
{
	QNN_SyncEngineCompat();
	/* Refresh cl_entities[] PVS visibility from this frame's packet
	 * entity list before QNN_CaptureBaseSnapshot → QNN_IOUpdate →
	 * QNN_StoreUpdate → QNN_EntityClassifyKnown reads the universe.
	 * Without this, baseline-seeded items leak through as always-PVS. */
	QNN_SyncPacketEntities();
	QNN_CaptureBaseSnapshot(snapshot);
	snapshot->done = reset_flag ? false : qnn_runtime.done;
	QNN_DrainSounds(snapshot);

	/* force_mvd_emit: scrub the QWD-only velocity signal.  The MVD
	 * parser never writes playerstate.velocity, so on a real MVD
	 * playback snapshot->player_velocity is always zero.  Under
	 * force_mvd_emit on a QWD demo, the snapshot capture path would
	 * otherwise fall through to QWD's svc_playerinfo velocity (the
	 * recorder's own velocity), which is QWD-specific signal the MVD
	 * inference path must not see.  Zero it so the rest of the
	 * pipeline operates on MVD-recoverable signals only. */
	if (qnn_runtime.force_mvd_emit && !cls.mvdplayback)
	{
		snapshot->player_velocity[0] = 0.0f;
		snapshot->player_velocity[1] = 0.0f;
		snapshot->player_velocity[2] = 0.0f;
	}
}

static qboolean QNN_ResetWorldLocal(const char *demo_path, char *error, size_t error_size)
{
	char command[QNN_WORKER_MAX_COMMAND_TEXT];
	int frame;

	if (qnn_map_state.map_name[0] == 0)
	{
		snprintf(error, error_size, "Call hello first so the worker knows which map to load");
		return false;
	}

	QNN_ClearAction(&qnn_pending_action);
	qnn_runtime.done = false;
	qnn_runtime.has_reset = false;
	qnn_runtime.mover_count = 0;
	qnn_runtime.player_count = 0;
	qnn_runtime.push_count = 0;
	qnn_sound_count = 0;
	QNN_TickEmitReset(&qnn_runtime.tick_emit);
	QNN_MvdCollectReset((uintptr_t)qnn_runtime.demo_path);
	QNN_QwdCollectReset();
	QNN_ResetPingEstimator();
	cls.demonum = -1;
	cls.timedemo = false;

	/* Clear per-demo entity / event / action state up front so that a
	 * mid-signon failure below can't leave stale qnn_store entries or
	 * mover/player indices visible to the next demo on this worker.
	 * The success path below re-runs QNN_IOInit to rebuild baselines
	 * from the newly-loaded demo. */
	QNN_IOInit(&qnn_map_state);

	CL_Disconnect();
	cls.state = ca_disconnected;

	/* Nuke any residual stufftext from the previous demo or
	 * Host_Init.  svc_stufftext messages in demos (cvar sets,
	 * disconnect, map loads) accumulate in cmd_text and would
	 * otherwise run before our playdemo, corrupting state. */
	{
		extern sizebuf_t cmd_text;
		SZ_Clear(&cmd_text);
	}

	snprintf(command, sizeof(command), "playdemo \"%s\"\n", demo_path);
	Cbuf_AddText(command);
	Cbuf_Execute();

	/* Pump frames until demo is loaded and active.  A working demo
	 * reaches ca_active within ~100 frames; if we haven't after 2048
	 * something is wrong (missing BSP, corrupt demo, etc.). */
	for (frame = 0; frame < 2048; ++frame)
	{
		Host_Frame(qnn_runtime.fixed_dt);
		if (QNN_ClientReady())
			break;
		if (frame > 0 && !cls.demoplayback && cls.state == ca_disconnected)
			break;
		/* Fail fast on missing BSP: QW parses the modellist early in
		 * signon, so cl.model_name[1] is set within a few frames. If
		 * that's set but cl.worldmodel is still NULL 256 frames later,
		 * Mod_ForName couldn't find the map file — no point pumping
		 * another 1792 frames waiting for ca_active. */
		if (frame >= 256 && cl.worldmodel == NULL && cl.model_name[1][0] != '\0')
		{
			fprintf(stderr, "[qw-demo] missing BSP: %s (worldmodel not loaded after %d frames)\n",
				cl.model_name[1], frame);
			snprintf(error, error_size, "Missing BSP %s for demo %s", cl.model_name[1], demo_path);
			return false;
		}
	}
	if (!QNN_ClientReady())
	{
		fprintf(stderr, "[qw-demo] playdemo failed: demoplayback=%d state=%d\n",
			cls.demoplayback, cls.state);
		if (!cls.demoplayback)
			snprintf(error, error_size,
				"demo_preamble_incompatible: %s (demoplayback ended during signon)",
				demo_path);
		else
			snprintf(error, error_size,
				"signon_timeout: %s (no ca_active after 2048 frames)",
				demo_path);
		return false;
	}

	/* Sync NQ compat state and baselines */
	QNN_SyncEngineCompat();
	QNN_SyncBaselines();

	/* Detection runs purely for diagnostic logging — it samples only
	 * the first few signon frames and is known to be inaccurate on
	 * demos that start mid-session.  It's no longer load-bearing for
	 * emit cadence: native-rate emission (tick_hz=0) drives off
	 * cls.netchan.incoming_sequence advance in the pump loop, and
	 * fixed-rate emission (tick_hz>0) gates at the explicit requested
	 * value via qnn_tick_hz.  Don't overwrite either knob here. */
	QNN_DetectNativeTickHz();

	/* Detect actual map from worldmodel */
	if (cl.worldmodel != NULL && cl.worldmodel->name[0] != '\0')
	{
		char demo_map[QNN_MAX_MAP_ID];
		const char *bsp_name = cl.worldmodel->name;
		const char *slash;
		const char *dot;
		size_t len;

		slash = strrchr(bsp_name, '/');
		if (slash != NULL)
			bsp_name = slash + 1;
		dot = strrchr(bsp_name, '.');
		len = dot ? (size_t)(dot - bsp_name) : strlen(bsp_name);
		if (len >= sizeof(demo_map))
			len = sizeof(demo_map) - 1;
		memcpy(demo_map, bsp_name, len);
		demo_map[len] = '\0';

		if (strcasecmp(demo_map, qnn_map_state.map_name) != 0)
		{
			char map_error[256];
			if (!QNN_PrepareMap(demo_map, map_error, sizeof(map_error)))
				fprintf(stderr, "[qw-demo] map rebuild for %s failed: %s\n", demo_map, map_error);
		}
	}

	qnn_runtime.tick = 0;
	qnn_runtime.steps = 0;
	qnn_runtime.has_reset = true;
	qnn_runtime.done = false;
	QNN_IOInit(&qnn_map_state);

	if (getenv("QNN_DUMP_TEAM") != NULL)
	{
		int slot;
		const char *teamplay = Info_ValueForKey(cl.serverinfo, "teamplay");
		const char *deathmatch = Info_ValueForKey(cl.serverinfo, "deathmatch");
		fprintf(stderr, "[team-dump] demo=%s\n", demo_path);
		fprintf(stderr, "[team-dump] cl.playernum=%d teamplay=\"%s\" deathmatch=\"%s\"\n",
			cl.playernum, teamplay, deathmatch);
		for (slot = 0; slot < MAX_CLIENTS; ++slot)
		{
			player_info_t *p = &cl.players[slot];
			const char *team;
			const char *topcolor;
			const char *bottomcolor;
			if (p->name[0] == '\0' && p->userinfo[0] == '\0')
				continue;
			team = Info_ValueForKey(p->userinfo, "team");
			topcolor = Info_ValueForKey(p->userinfo, "topcolor");
			bottomcolor = Info_ValueForKey(p->userinfo, "bottomcolor");
			{
				char team_hex[64];
				size_t i, n = strlen(team);
				if (n > sizeof(team_hex) / 3 - 1)
					n = sizeof(team_hex) / 3 - 1;
				team_hex[0] = '\0';
				for (i = 0; i < n; ++i)
					snprintf(team_hex + i * 3, 4, "%02x ", (unsigned char)team[i]);
				fprintf(stderr,
					"[team-dump] slot=%2d name=\"%s\" spec=%d team_hex=[%s] top=\"%s\" bot=\"%s\"%s\n",
					slot, p->name, p->spectator, team_hex, topcolor, bottomcolor,
					(slot == cl.playernum) ? " <-- recorder" : "");
			}
		}
		fflush(stderr);
	}

	return true;
}

static void QNN_WriteHelloResponse(void)
{
	fprintf(stdout, "{\"capabilities\":[\"demo_playback\",\"qw_demo\",\"mvd_demo\",\"navmesh_query_v1\",\"obs_buffer_collect_v1\"],\"map_id\":");
	QNN_WriteJsonString(stdout, qnn_map_state.requested_map_id);
	fprintf(stdout, ",\"ok\":true,\"protocol_version\":");
	QNN_WriteJsonString(stdout, QNN_WORKER_PROTOCOL);
	fprintf(stdout, ",\"server\":");
	QNN_WriteJsonString(stdout, QNN_WORKER_SERVER_NAME);
	fprintf(stdout, ",\"tick_hz\":%d,\"worker_build\":{\"basedir\":", qnn_runtime.fixed_tick_hz);
	QNN_WriteJsonString(stdout, basedir);
	fprintf(stdout, ",\"upstream_commit\":");
	QNN_WriteJsonString(stdout, QNN_WORKER_UPSTREAM_COMMIT);
	fprintf(stdout, "}}\n");
	fflush(stdout);
}

/* QNN_OpIs — shared in common/qnn_collect_helpers.c. */

static int QNN_HandleHello(const char *line)
{
	char map_id[QNN_MAX_MAP_ID];
	char error[256];

	memset(map_id, 0, sizeof(map_id));
	memset(error, 0, sizeof(error));
	if (!QNN_JsonExtractString(line, "\"map_id\"", map_id, sizeof(map_id)))
		snprintf(map_id, sizeof(map_id), "dm3");

	{
		/* hello.tick_hz = 0 → emit at the demo's native recording rate.
		 * We can't know that rate until DetectNativeTickHz runs (post-
		 * signon), so park fixed_tick_hz at the sentinel 0 here and use
		 * a safe 77 Hz fixed_dt for signon-phase Host_Frame calls.
		 * QNN_HandleCollect resolves the sentinel against
		 * native_hz_detected immediately after signon. */
		int tick_hz = QNN_JsonExtractInt(line, "\"tick_hz\"", 20);
		if (tick_hz < 0) tick_hz = 0;
		qnn_runtime.requested_tick_hz = tick_hz;
		qnn_runtime.fixed_tick_hz = tick_hz;
		qnn_runtime.fixed_dt = (tick_hz > 0)
			? 1.0f / (float)tick_hz
			: 1.0f / 77.0f;
		Cvar_SetValue("qnn_tick_hz",
			(float)(tick_hz > 0 ? tick_hz : 77));
	}

	if (!QNN_PrepareMap(map_id, error, sizeof(error)))
	{
		QNN_WriteError(error);
		return 0;
	}

	QNN_WriteHelloResponse();
	return 0;
}

/* MVD carries no attack_finished (the QC VM never sees usercmds, so
 * W_Attack never stamps it).  On a detected attack, stamp
 * attack_finished = now + the weapon's QC cooldown so the obs scalar and
 * the input-mask attack-feasibility bit reflect the engine lockout.
 * Cooldown is owned by qnn_weapon.c (raw weapon id 1..8). */
/* QC-feasibility callback for the MVD intent label (weapon-head.md §12
 * parity): same predicate the QWD machine uses (QNN_QwdEvalSelect →
 * QNN_ProgsEvalWeaponImpulse), answering "would W_ChangeWeapon accept a
 * direct select of `weapon` given the snapshot's items/ammo".  Returns 0
 * when the progs VM is unavailable (bare real-.mvd playback) — every
 * held change then re-baselines, degrading toward held-tracking rather
 * than inventing intent. */
static int QNN_MvdSelectFeasible(const qnn_snapshot_t *snapshot,
	int current, int weapon)
{
	int cand = QNN_ImpulseFromItemFlag(QNN_ProgsEvalWeaponImpulse(
		snapshot->health, snapshot->items_owned,
		snapshot->ammo_shells, snapshot->ammo_nails,
		snapshot->ammo_rockets, snapshot->ammo_cells,
		current, weapon));
	return cand == weapon;
}

static void QNN_MvdStampAttackFinished(int weapon_id, float now_seconds)
{
	float done_sec;

	if (!QNN_WeaponIsValid(weapon_id))
		return;
	done_sec = now_seconds + QNN_WeaponCooldownSec(weapon_id);
	if (done_sec > QNN_ProgsGetAttackFinished())
		QNN_ProgsSetAttackFinished(done_sec);
}

/* enumerate_players — signon-only pass over an MVD; reports the valid
 * non-spectator player slots so the controller can dispatch one collect
 * per slot (approach A, single-POV per pass).  Output is a single JSON
 * line: {"players":[{"slot":N,"name":"..."},...]}.  Ungated demux so
 * every slot is observed. */
static int QNN_HandleEnumeratePlayers(const char *line)
{
	char demo_path[MAX_OSPATH];
	char error[256];
	int p, first;

	memset(demo_path, 0, sizeof(demo_path));
	memset(error, 0, sizeof(error));
	if (!QNN_JsonExtractString(line, "\"demo_path\"", demo_path, sizeof(demo_path)))
	{
		QNN_WriteError("enumerate_players requires demo_path");
		return 0;
	}
	Q_strncpy(qnn_runtime.demo_path, demo_path, sizeof(qnn_runtime.demo_path) - 1);
	qnn_runtime.demo_path[sizeof(qnn_runtime.demo_path) - 1] = '\0';
	QNN_FaultSetContext(demo_path);

	/* Ungated: observe every player's signon so we see all slots. */
	qnn_mvd_anchor_player = -1;
	if (!QNN_ResetWorldLocal(demo_path, error, sizeof(error)))
	{
		QNN_WriteError(error);
		QNN_FaultSetContext(NULL);
		return 0;
	}

	/* Emit slots only — QW player names use the Quake charset (high-bit
	 * bytes) and aren't valid UTF-8, which the JSON reader can't decode.
	 * The controller only needs the slots; names are logged to stderr
	 * during the per-slot collect for humans. */
	fprintf(stdout, "{\"slots\":[");
	first = 1;
	for (p = 0; p < MAX_CLIENTS; ++p)
	{
		if (cl.players[p].name[0] == '\0' || cl.players[p].spectator)
			continue;
		fprintf(stdout, "%s%d", first ? "" : ",", p);
		first = 0;
	}
	fprintf(stdout, "]}\n");
	fflush(stdout);
	QNN_FaultSetContext(NULL);
	return 0;
}

/* ── Matched-emit native-rate pass ───────────────────────────────────
 *
 * One native-dt replay that emits TWO interleaved framed streams:
 *
 *   MLOB (every native frame): the slim move-labeler record — view-frame
 *     per-native-frame velocity, self_movement_id / self_weapon_id, and
 *     usercmd-TRUTH move/look/op_input (always the QWD decoder, even when
 *     the run sets force_mvd_emit — the labeler trains on MVD-domain obs
 *     with truth labels).  native_index = qnn_runtime.tick.
 *
 *   QOBS (each 20 Hz cl.mtime boundary): the full model corpus frame, with
 *     derivatives computed over the 20 Hz interval (anchored at the
 *     previous boundary): vel = (origin_now − origin_prev_boundary) /
 *     interval_dt, look / look_delta relative to the previous boundary's
 *     view (via QNN_SaveEmitAnchor's emit_view_angles + the IOEmit
 *     look_delta carry).  The current native index is stamped into the
 *     QOBS header `steps` field so labeler predictions can be resampled to
 *     20 Hz by exact index lookup.
 *
 * No back-shift ring / no jitter filter on this path: the slim stream is
 * raw per-native-frame truth (the labeler owns any smoothing), and the
 * QOBS frames are emitted directly (QNN_EmitTick) at the boundary so the
 * native_index stamp is exact.  force_mvd_emit affects only obs velocity
 * sourcing (handled the same way as the single-stream loop). */
static void QNN_RunMatchedEmit(qnn_snapshot_t *snapshot,
	qnn_snapshot_t *label_snapshot, int play_start, int play_end)
{
	const qboolean mvd_path =
		(cls.mvdplayback || qnn_runtime.force_mvd_emit);
	const float NATIVE_PROBE_DT = 0.001f;
	const int NATIVE_PUMPS_PER_FRAME_MAX = 4096;
	qboolean emitting = false;
	/* 20 Hz demo-time boundary tracking. */
	int last_boundary = -1;
	qboolean have_boundary_anchor = false;
	vec3_t boundary_origin = {0, 0, 0};
	double boundary_mtime = 0.0;

	QNN_WatchdogBegin(10);
	while (!qnn_runtime.done)
	{
		float tick_start_attack_finished;
		int prev_seq;
		int pumps;
		float actual_dt;
		int cur_boundary;

		qnn_runtime.cmd_seq_window_start = cls.netchan.outgoing_sequence;
		qnn_runtime.emit_start_native = (float)cl.time;
		QNN_CaptureSnapshotLocal(snapshot, false);
		tick_start_attack_finished = QNN_ProgsGetAttackFinished();

		/* Native step: pump 1 ms frames until one server frame is consumed. */
		prev_seq = cls.netchan.incoming_sequence;
		pumps = 0;
		while (cls.netchan.incoming_sequence == prev_seq
			&& cls.demoplayback
			&& cls.state != ca_disconnected
			&& pumps < NATIVE_PUMPS_PER_FRAME_MAX)
		{
			Host_Frame(NATIVE_PROBE_DT);
			pumps++;
		}
		actual_dt = (float)cl.time - qnn_runtime.emit_start_native;
		if (actual_dt > 0.0001f)
			qnn_runtime.fixed_dt = actual_dt;

		QNN_WatchdogTick();
		qnn_runtime.tick += 1;
		qnn_runtime.steps += 1;

		/* Mid-demo map change: rebuild physics refs (same as the
		 * single-stream loop). */
		if ((void *)cl.worldmodel != qnn_runtime.refs_worldmodel
			&& QNN_ClientReady())
		{
			QNN_SyncEngineCompat();
			QNN_SyncBaselines();
			QNN_BuildAllRefs();
			QNN_PhysInit();
			qnn_runtime.refs_worldmodel = (void *)cl.worldmodel;
		}

		if (!cls.demoplayback || cls.state == ca_disconnected)
			qnn_runtime.done = true;
		if (!qnn_runtime.done)
			QNN_CaptureSnapshotLocal(label_snapshot, false);
		else
		{
			*label_snapshot = *snapshot;
			snapshot->done = true;
			label_snapshot->done = true;
		}

		if (qnn_runtime.tick > play_end)
		{
			snapshot->done = true;
			label_snapshot->done = true;
			qnn_runtime.done = true;
		}

		if (!emitting && qnn_runtime.tick >= play_start)
		{
			emitting = true;
			QNN_IOUpdate(snapshot, qnn_runtime.fixed_dt, true);
			QNN_SaveEmitAnchor(snapshot);
		}
		if (!emitting && !qnn_runtime.done)
		{
			QNN_SavePrev(label_snapshot, qnn_runtime.fixed_dt);
			continue;
		}
		if (!emitting)
			continue;

		/* MVD-recoverable obs velocity (matches the single-stream loop:
		 * the MVD parser delivers no playerstate velocity, so feed the
		 * origin-delta estimate into the obs snapshot). */
		if (mvd_path)
			VectorCopy(qnn_runtime.prev_velocity, snapshot->player_velocity);

		if (qnn_runtime.tick > play_start)
			QNN_IOUpdate(snapshot, qnn_runtime.fixed_dt, false);

		/* ── Slim MLOB record: usercmd-TRUTH labels, every native frame ──
		 * Feature fields (vel / movement_id / weapon_id) are sourced from
		 * the PRE-frame `snapshot` so they frame identically to the QOBS at
		 * the same native_index (the QOBS obs is also packed from the
		 * pre-frame snapshot — decision-time input).  The action label is
		 * the usercmd-truth move/look/op_input decoded over the cmd window
		 * consumed this Host_Frame, built on the label snapshot regardless
		 * of force_mvd_emit so the labeler trains on truth labels. */
		if (!snapshot->done)
		{
			qnn_mlob_record_t rec;
			vec3_t vel_view;

			memset(&rec, 0, sizeof(rec));
			QNN_QwdBuildActionLabel(&label_snapshot->action_label, label_snapshot);
			QNN_FillLookAndSwitch(&label_snapshot->action_label, label_snapshot);

			rec.native_index = (uint32_t)qnn_runtime.tick;
			rec.flags = 0;
			/* Per-native-frame velocity, view-frame (same transform
			 * QNN_SelfEmitToken applies to the obs vel).  Uses the pre-frame
			 * snapshot's velocity so it matches the obs vel field framing;
			 * on the MVD path snapshot->player_velocity was set to the
			 * origin-delta estimate above. */
			QNN_RelativeFrame(snapshot->player_view_angles,
				snapshot->player_velocity, vel_view);
			rec.vel[0] = QNN_QuantizeI16Clamped(vel_view[0], QNN_VELOCITY_SCALE);
			rec.vel[1] = QNN_QuantizeI16Clamped(vel_view[1], QNN_VELOCITY_SCALE);
			rec.vel[2] = QNN_QuantizeI16Clamped(vel_view[2], QNN_VELOCITY_SCALE);
			switch (snapshot->waterlevel)
			{
			case 1: rec.self_movement_id = 2; break;
			case 2: rec.self_movement_id = 3; break;
			case 3: rec.self_movement_id = 4; break;
			default: rec.self_movement_id =
				snapshot->grounded ? 0 : 1; break;
			}
			rec.self_weapon_id =
				(uint8_t)qnn_weapon_subject_from_id(snapshot->weapon_id);
			rec.action = label_snapshot->action_label;
			QNN_EmitMlob(stdout, &rec);
		}

		/* ── 20 Hz QOBS boundary emission ───────────────────────────────
		 * Demo-time boundary = floor(cl.mtime[0] * 20).  Emit one QOBS
		 * each time the boundary index advances, with interval-correct
		 * derivatives anchored at the previous boundary. */
		cur_boundary = (int)floor((double)cl.mtime[0] * 20.0);
		if (!snapshot->done && cur_boundary != last_boundary)
		{
			uint8_t obs_bytes[QNN_OBS_BUFFER_SIZE];
			qnn_snapshot_t obs_snap = *snapshot;
			float interval_dt;

			/* Interval velocity over the previous 20 Hz boundary → now.
			 * QNN_SelfEmitToken rotates player_velocity into the view
			 * frame, so write the world-frame interval velocity here. */
			if (have_boundary_anchor
				&& (interval_dt = (float)(cl.mtime[0] - boundary_mtime)) > 0.0001f)
			{
				vec3_t ivel;
				int k;
				for (k = 0; k < 3; k++)
					ivel[k] = (obs_snap.player_origin[k]
						- boundary_origin[k]) / interval_dt;
				VectorCopy(ivel, obs_snap.player_velocity);
			}
			/* else: first boundary — leave snapshot velocity as-is. */

			/* look / look_delta anchor at the previous boundary view: the
			 * emit anchor (emit_view_angles) was last saved at the prior
			 * boundary, and the IOEmit look_delta carry advances only on
			 * QOBS emits (QNN_IOUpdate ran above with reset only at
			 * play_start). */
			{
				float saved_af = QNN_ProgsGetAttackFinished();
				QNN_ProgsSetAttackFinished(tick_start_attack_finished);
				QNN_PackSnapshotObs(&obs_snap, obs_bytes);
				QNN_ProgsSetAttackFinished(saved_af);
			}

			/* Build the QOBS action label.  On the genuine QWD path this is
			 * the usercmd decoder; under force_mvd_emit the single-stream
			 * loop runs MVD inference, but the matched corpus QOBS keeps the
			 * usercmd-truth label here too (the labeler-resample rewrite is
			 * what later supplies MVD-domain move; co-emitting truth keeps
			 * the QOBS self-consistent and avoids the back-shift machinery). */
			QNN_QwdBuildActionLabel(&obs_snap.action_label, &obs_snap);
			QNN_FillLookAndSwitch(&obs_snap.action_label, &obs_snap);

			/* steps field carries the native index this QOBS was sampled
			 * at (reused — downstream QOBS parser ignores steps). */
			QNN_EmitTick(stdout, obs_bytes, &obs_snap.action_label,
				qnn_runtime.tick, /*steps=*/qnn_runtime.tick,
				/*tick_hz=*/20, /*flags=*/0);

			/* Advance the boundary anchor for the next interval. */
			QNN_SaveEmitAnchor(snapshot);
			VectorCopy(snapshot->player_origin, boundary_origin);
			boundary_mtime = cl.mtime[0];
			have_boundary_anchor = true;
			last_boundary = cur_boundary;
		}

		QNN_SavePrev(label_snapshot, qnn_runtime.fixed_dt);
	}
	QNN_WatchdogEnd();

	/* Terminate both streams with a done frame so the Python demux unblocks.
	 * A zero-token done QOBS carries FLAG_DONE; the MLOB stream's done is
	 * signalled by the same flag on a trailing MLOB. */
	{
		qnn_mlob_record_t done_rec;
		memset(&done_rec, 0, sizeof(done_rec));
		done_rec.native_index = (uint32_t)qnn_runtime.tick;
		done_rec.flags = QNN_FLAG_DONE;
		QNN_EmitMlob(stdout, &done_rec);

		snapshot->done = true;
		QNN_WriteObsTick(&qnn_runtime.tick_emit, stdout, snapshot,
			qnn_runtime.tick, qnn_runtime.tick, 20, true);
	}
}

static int QNN_HandleCollect(const char *line)
{
	qnn_action_t native_action;
	qnn_snapshot_t snapshot;
	qnn_snapshot_t label_snapshot;
	char demo_path[MAX_OSPATH];
	char error[256];
	int mvd_player_num;

	int play_start, play_end;

	memset(demo_path, 0, sizeof(demo_path));
	memset(error, 0, sizeof(error));
	mvd_player_num = QNN_JsonExtractInt(line, "\"player_num\"", -1);
	play_start = QNN_JsonExtractInt(line, "\"play_start\"", 0);
	play_end = QNN_JsonExtractInt(line, "\"play_end\"", 999999999);
	qnn_runtime.force_mvd_emit = QNN_JsonExtractInt(line, "\"force_mvd_emit\"", 0) != 0;
	/* usercmd_move (default 0): under force_mvd_emit on a QWD demo, take the
	 * `move` action from the usercmd-truth decoder instead of MVD physics
	 * inference, leaving obs features MVD-domain.  The force_mvd LOBS labeler
	 * collect sends =1; everywhere else =0 keeps the physics move unchanged. */
	qnn_runtime.usercmd_move   = QNN_JsonExtractInt(line, "\"usercmd_move\"", 0) != 0;
	/* Compute-gate selection (default OFF skip → full BC collect
	 * unchanged).  A slim subset collect passes skip_spatial=1 /
	 * skip_entities=1 to skip the spatial raycast + entity oracle/
	 * pathfinding entirely; the obs buffer then carries those blocks
	 * zeroed and the Python projection drops them before disk. */
	qnn_runtime.skip_spatial   = QNN_JsonExtractInt(line, "\"skip_spatial\"",  0) != 0;
	qnn_runtime.skip_entities  = QNN_JsonExtractInt(line, "\"skip_entities\"", 0) != 0;
	/* Matched-emit mode: one native-rate pass emits a slim MLOB record per
	 * native frame plus a full QOBS at every 20 Hz demo-time boundary (see
	 * qnn_runtime_t.matched_emit).  Requires native-rate playback
	 * (requested_tick_hz==0); the controller pairs it with tick_hz:0 hello. */
	qnn_runtime.matched_emit   = QNN_JsonExtractInt(line, "\"matched_emit\"", 0) != 0;
	/* Attack-script fingerprint for the de-scripted weapon intent label
	 * (weapon-head.md §10-11); 0/0 default = unscripted demo. */
	qnn_runtime.weapon_script  = QNN_JsonExtractInt(line, "\"weapon_script\"", 0) != 0;
	qnn_runtime.weapon_release = QNN_JsonExtractInt(line, "\"weapon_release\"", 0);
	if (!QNN_JsonExtractString(line, "\"demo_path\"", demo_path, sizeof(demo_path)))
	{
		QNN_WriteError("reset options must include demo_path");
		return 0;
	}
	Q_strncpy(qnn_runtime.demo_path, demo_path, sizeof(qnn_runtime.demo_path) - 1);
	qnn_runtime.demo_path[sizeof(qnn_runtime.demo_path) - 1] = '\0';
	QNN_FaultSetContext(demo_path);
	/* Leave the demux ungated through signon (serverdata/modellist/
	 * userinfo may arrive on per-recipient blocks the anchor isn't in).
	 * We lock the anchor below, once the tracked slot is chosen. */
	qnn_mvd_anchor_player = -1;
	if (!QNN_ResetWorldLocal(demo_path, error, sizeof(error)))
	{
		QNN_WriteError(error);
		QNN_FaultSetContext(NULL);
		return 0;
	}

	/* QC VM init must happen AFTER QNN_ResetWorldLocal: the world reset
	 * resets the QW client's hunk (Host_ClearMemory), which would wipe
	 * any memory PR_LoadProgs had allocated for progs/pr_functions/
	 * pr_strings/etc.  Initializing here puts the QC bytecode at the
	 * top of the hunk where it stays valid for the duration of demo
	 * playback.  QC VM is the canonical source of truth for the labeler's
	 * op_input (attack / jump operativeness) — if it fails to load,
	 * the worker has no principled sanitization, so we hard-fail. */
	if (!QNN_ProgsInit())
	{
		QNN_WriteError("qnn_progs: QC VM init failed (qwprogs.dat missing or "
			"version mismatch).  Labeler-mode collect requires QC VM for "
			"op_input sanitization.");
		QNN_FaultSetContext(NULL);
		return 0;
	}

	/* cl_nopred: always run prediction.
	 *
	 * Prediction is left on regardless of mode because CL_PredictMove
	 * is also what keeps the engine's module-level `waterlevel` and the
	 * playerstate `onground` field current in QWD playback — turning
	 * it off collapses snapshot->grounded/waterlevel to a single regime
	 * (100% ground) and breaks the labeler's movement_id feature.
	 *
	 * QWD leakage from pmove is suppressed at the source: under
	 * force_mvd_emit, qnn_self.c QNN_CaptureBaseSnapshot
	 * routes origin/velocity through the server playerstate
	 * (ps->origin / ps->velocity) instead of the pmove-driven
	 * cl.simorg / cl.simvel, and QNN_CaptureSnapshotLocal then zeros
	 * player_velocity to match real MVD (MVD parser never writes
	 * playerstate.velocity). */
	Cvar_Set("cl_nopred", "0");

	/* MVD: select tracked player and initialize physics inference.
	 * Tick rate already detected in QNN_ResetWorldLocal via
	 * QNN_DetectNativeTickHz (~77 Hz on MVDSV, varies elsewhere). */
	if (cls.mvdplayback)
	{
		/* Require an explicit, valid tracked player.  The controller
		 * enumerates slots (op "enumerate_players") and dispatches one
		 * collect per slot, so player_num is always supplied.  No
		 * auto-select: a single-POV stream needs an unambiguous anchor,
		 * and silently picking the first slot would mislabel which
		 * player's trajectory this collect represents. */
		if (mvd_player_num < 0 || mvd_player_num >= MAX_CLIENTS
			|| cl.players[mvd_player_num].name[0] == '\0'
			|| cl.players[mvd_player_num].spectator)
		{
			snprintf(error, sizeof(error),
				"mvd collect requires a valid non-spectator player_num "
				"(got %d) — call enumerate_players first", mvd_player_num);
			QNN_WriteError(error);
			QNN_FaultSetContext(NULL);
			return 0;
		}
		cl.playernum = mvd_player_num;
		fprintf(stderr, "[qw-demo] MVD tracking player %d: %s\n",
			cl.playernum, cl.players[cl.playernum].name);

		/* Lock the per-recipient demux to the tracked slot: from here on
		 * CL_GetMVDMessage skips dem_single/dem_multiple blocks not
		 * addressed to this player, so events/sounds match exactly what
		 * the tracked player received (its own weapon-attack sound always
		 * included; attacks it never heard excluded — no cross-player
		 * pollution of the sound-derived labels). */
		qnn_mvd_anchor_player = cl.playernum;
	}

	/* Initialize BSP-clipped physics for any path that will call into
	 * PlayerMove() during this demo: MVD movement inference, QWD MVD-
	 * inference (force_mvd_emit).  The genuine QWD path's per-cmd pmove
	 * jump driver (QNN_QwdEvalPmoveJump) self-seeds physents[0] from
	 * cl.worldmodel each call, so it does not require this global init.
	 * Without this, pmove.physents[0].model points at the previous
	 * demo's freed worldmodel (or NULL on the first demo) and the next
	 * trace SEGVs. */
	if (cls.mvdplayback || qnn_runtime.force_mvd_emit)
		QNN_PhysInit();

	/* Engine tick = emit tick.  fixed_dt was set from hello.tick_hz and
	 * matches qnn_tick_hz cvar; QNN_TickGate in cl_main.c lets every
	 * Host_Frame(fixed_dt) call advance.  No resample aggregation. */

	/* play_start / play_end arrive as native-frame indices.  In native
	 * mode (tick_hz == 0) qnn_runtime.tick increments once per consumed
	 * server frame, so the values are already in the right space —
	 * skip the rescale.  In fixed-rate mode, qnn_runtime.tick increments
	 * at fixed_tick_hz, so rescale by fixed_tick_hz / native_hz_detected.
	 * Falls back to 77 Hz QW if detection produced no value. */
	if (qnn_runtime.fixed_tick_hz > 0)
	{
		int native_hz = qnn_runtime.native_hz_detected > 0
			? qnn_runtime.native_hz_detected
			: 77;
		if (play_start > 0)
			play_start = (int)(((long long)play_start * qnn_runtime.fixed_tick_hz) / native_hz);
		if (play_end < 999999999)
			play_end = (int)(((long long)play_end * qnn_runtime.fixed_tick_hz) / native_hz);
		fprintf(stderr, "[qw-demo] play gate (native→emit @ %d Hz / %d Hz): play_start=%d play_end=%d\n",
			native_hz, qnn_runtime.fixed_tick_hz, play_start, play_end);
	}
	else
	{
		fprintf(stderr, "[qw-demo] play gate (native emit, no rescale): play_start=%d play_end=%d\n",
			play_start, play_end);
	}

	/* Matched-emit mode is a distinct native-rate pass: it interleaves a
	 * slim MLOB stream (per native frame) with the 20 Hz QOBS corpus on
	 * one pipe.  Handled in its own loop to keep the single-stream emit
	 * path below unchanged; shares all the signon / QC VM / physics /
	 * play-gate setup done above. */
	if (qnn_runtime.matched_emit)
	{
		QNN_RunMatchedEmit(&snapshot, &label_snapshot, play_start, play_end);
		fflush(stdout);
		if (qnn_runtime.store_dump != NULL)
		{
			fflush(qnn_runtime.store_dump);
			fclose(qnn_runtime.store_dump);
			qnn_runtime.store_dump = NULL;
		}
		QNN_FaultSetContext(NULL);
		return 0;
	}

	{
		int emit_hz = qnn_runtime.fixed_tick_hz;
		/* MVD inference path: a real MVD, or a QWD replayed under
		 * force_mvd_emit for parity validation.  Computed once here;
		 * every emit-loop branch below keys off this single predicate. */
		const qboolean mvd_path =
			(cls.mvdplayback || qnn_runtime.force_mvd_emit);

		QNN_CaptureSnapshotLocal(&snapshot, true);
		QNN_SavePrev(&snapshot, 0.0f);
		QNN_SaveEmitAnchor(&snapshot);
		QNN_IOUpdate(&snapshot, qnn_runtime.fixed_dt, true);
		QNN_BuildAllRefs();
		qnn_runtime.refs_worldmodel = (void *)cl.worldmodel;

		{
			qboolean emitting = false;

		QNN_WatchdogBegin(10);
		/* Native-rate emission (tick_hz=0): pump small Host_Frame steps
		 * until cls.netchan.incoming_sequence advances (= the engine
		 * consumed one DEM_READ record), then run the emit body once
		 * with fixed_dt set to the actual elapsed cl.time.  This makes
		 * the emit count track the demo's DEM_READ count independent
		 * of QNN_DetectNativeTickHz's accuracy.
		 *
		 * Fixed-rate mode (tick_hz>0): one Host_Frame(fixed_dt) per
		 * emit, engine consumes whatever DEM_READs land in that
		 * interval (vendor behavior).  qnn_tick_hz cvar gates the
		 * advance at the requested rate. */
		const qboolean native_emit_mode = (qnn_runtime.requested_tick_hz == 0);
		const float NATIVE_PROBE_DT = 0.001f;
		const int NATIVE_PUMPS_PER_FRAME_MAX = 4096;  /* 4.1s cap */
		while (!qnn_runtime.done)
		{
			float tick_start_attack_finished = 0.0f;

			qnn_runtime.cmd_seq_window_start = cls.netchan.outgoing_sequence;
			qnn_runtime.emit_start_native = (float)cl.time;
			QNN_CaptureSnapshotLocal(&snapshot, false);
			/* Snapshot the QC VM's attack_finished BEFORE Host_Frame
			 * consumes this tick's demo cmd and before any action label
			 * code advances the cooldown by this tick's attack. The obs
			 * must record decision-time AF, not post-action AF. */
			tick_start_attack_finished =
				QNN_ProgsGetAttackFinished();
			if (native_emit_mode)
			{
				int prev_seq = cls.netchan.incoming_sequence;
				int pumps = 0;
				while (cls.netchan.incoming_sequence == prev_seq
					&& cls.demoplayback
					&& cls.state != ca_disconnected
					&& pumps < NATIVE_PUMPS_PER_FRAME_MAX)
				{
					Host_Frame(NATIVE_PROBE_DT);
					pumps++;
				}
				/* Stamp fixed_dt with the actual server-frame period
				 * for this emit so downstream consumers see real
				 * elapsed time. */
				float actual_dt = (float)cl.time - qnn_runtime.emit_start_native;
				if (actual_dt > 0.0001f)
					qnn_runtime.fixed_dt = actual_dt;
			}
			else
			{
				Host_Frame(qnn_runtime.fixed_dt);
			}
			QNN_WatchdogTick();
			qnn_runtime.tick += 1;
			qnn_runtime.steps += 1;

			/* Mid-demo map change: a fresh svc_serverdata repointed
			 * cl.worldmodel and reset per-map state.  Rebuild the
			 * mover/player/push refs (and re-seed pmove) against the new
			 * map once it's fully active — the old refs carry stale
			 * model_precache indices that now resolve to the new map's
			 * non-bmodel (.mdl) slots, faulting PM_RecursiveHullCheck.
			 * Until this fires, QNN_QwdEvalPmoveJump skips on the same
			 * refs_worldmodel mismatch so no trace runs cross-map.  The QC
			 * VM is reloaded independently via the CL_ParseServerData hook. */
			if ((void *)cl.worldmodel != qnn_runtime.refs_worldmodel
				&& QNN_ClientReady())
			{
				QNN_SyncEngineCompat();
				QNN_SyncBaselines();
				QNN_BuildAllRefs();
				QNN_PhysInit();
				qnn_runtime.refs_worldmodel = (void *)cl.worldmodel;
				fprintf(stderr,
					"[qw-demo] map change: rebuilt physics refs for %s at tick %d\n",
					cl.worldmodel->name, qnn_runtime.tick);
			}

			if (!cls.demoplayback || cls.state == ca_disconnected)
				qnn_runtime.done = true;
			if (!qnn_runtime.done)
				QNN_CaptureSnapshotLocal(&label_snapshot, false);
			else
			{
				label_snapshot = snapshot;
				snapshot.done = true;
				label_snapshot.done = true;
			}

			/* Frame-gated emission: play_start..play_end from the
			 * offline analyzer.  Everything outside is skipped. */
			if (qnn_runtime.tick > play_end)
			{
				snapshot.done = true;
				label_snapshot.done = true;
				qnn_runtime.done = true;
			}

			if (!emitting && qnn_runtime.tick >= play_start)
			{
				emitting = true;
				QNN_IOUpdate(&snapshot, qnn_runtime.fixed_dt, true);
				QNN_SaveEmitAnchor(&snapshot);
				fprintf(stderr, "[qw-demo] emitting from tick %d (play_start=%d play_end=%d)\n",
					qnn_runtime.tick, play_start, play_end);
			}

			if (!emitting && !qnn_runtime.done)
			{
				QNN_SavePrev(&label_snapshot, qnn_runtime.fixed_dt);
				continue;
			}
			if (!emitting)
				continue;

			/* MVD-recoverable velocity for the obs stream.  The MVD
			 * parser never delivers playerstate velocity (and the
			 * QWD-only simvel is scrubbed under force_mvd_emit), so
			 * obs vel on MVD-path collects would otherwise be all
			 * zero — an obs-distribution gap against QWD training
			 * data and a dead input for the offline move relabeler.
			 * prev_velocity at this point is the origin delta over
			 * the previous emit tick: SavePrev ran on the post-frame
			 * label snapshots of t-1/t-2, and post[t-1] == pre[t],
			 * so it equals (pre[t] - pre[t-1]) / dt — the trailing
			 * estimate a real MVD can recover.  Written to the obs
			 * snapshot only; label inference reads emit_velocity /
			 * prev_snap_velocity and is unchanged. */
			if (mvd_path)
				VectorCopy(qnn_runtime.prev_velocity,
					snapshot.player_velocity);

			if (emitting && qnn_runtime.tick > play_start)
				QNN_IOUpdate(&snapshot, qnn_runtime.fixed_dt, false);

			if (qnn_runtime.store_dump != NULL)
			{
				QNN_StoreDumpSounds(qnn_runtime.store_dump, qnn_runtime.tick, &snapshot);
				QNN_StoreDumpTick(qnn_runtime.store_dump, qnn_runtime.tick, (float)cl.mtime[0]);
			}

			/* Buffer per-native-frame mover and other-player positions
			 * so the emission-time physics inference can set up the
			 * correct BSP collision state for the 9 candidates. */
			if (mvd_path && !snapshot.done)
			{
				int nf = qnn_runtime.native_frame_count;
				if (nf < QNN_MAX_NATIVE_FRAMES)
				{
					int m;
					for (m = 0; m < qnn_runtime.mover_count; m++)
					{
						entity_t *me = &cl_entities[qnn_runtime.mover_entity_nums[m]];
						VectorCopy(me->origin, qnn_runtime.mover_origins[nf][m]);
					}
					for (m = 0; m < qnn_runtime.player_count; m++)
					{
						int entnum = qnn_runtime.player_entity_nums[m];
						VectorCopy(qnn_store[entnum].origin,
							qnn_runtime.player_origins[nf][m]);
					}
					qnn_runtime.native_frame_count = nf + 1;
				}
			}

			/* Extract per-frame action (MVD path only).
			 *
			 * MVD branch carries a real side effect:
			 * QNN_MvdInferNativeAction sets
			 * qnn_runtime.native_attack_this_window for the back-shift
			 * attack emit downstream.
			 *
			 * QWD branch was a dead call: native_action is
			 * write-only across this function, so the only effect of
			 * calling QwdExtractAction here was advancing
			 * qnn_progs_attack_finished a second time within the same
			 * tick — QwdBuildActionLabel (line below) internally calls
			 * QwdExtractAction once per tick already, and the per-cmd
			 * loop's QNN_ProgsEvalAttack on the second call saw the
			 * just-set future attack_finished and rejected every
			 * attack, leaving qwd_state.last_op_attack = 0 in the stash
			 * QwdPackInputMask reads. Result: input_mask bit 0
			 * (attack) never set across the BC QWD corpus. Same
			 * failure mode commit 4c7c9b4d fixed for the labeler
			 * path. */
			if (!snapshot.done)
			{
				if (mvd_path)
					QNN_MvdInferNativeAction(&native_action,
						&label_snapshot);
			}

			/* Emit-time action label.  QWD path is a pure usercmd-byte
			 * decoder (action.weapon written canonically inside
			 * QNN_QwdBuildActionLabel); MVD path runs inference. */
			if (!snapshot.done)
			{
				if (mvd_path)
				{
					float phys_dt;
					QNN_MvdInferEmitAction(
						&label_snapshot.action_label,
						&label_snapshot);
					phys_dt = qnn_runtime.native_frame_count
						* qnn_runtime.fixed_dt;
					if (phys_dt > 0.0f)
					{
						QNN_MvdInferEmitMove(
							&label_snapshot.action_label,
							&label_snapshot, phys_dt);
						qnn_runtime.prev_move = label_snapshot.action_label.move;
					}
					else
					{
						label_snapshot.action_label.move = qnn_runtime.prev_move;
					}
					QNN_MvdPackInputMask(
						&label_snapshot.action_label,
						&label_snapshot,
						tick_start_attack_finished);
					/* usercmd_move decouple: features stay MVD-domain
					 * (obs velocity scrubbed/origin-delta above), but the
					 * `move` action is taken from the usercmd-TRUTH QWD
					 * decoder instead of the 9-candidate physics inference.
					 * QWD demos still carry usercmd_t, so QwdBuildActionLabel
					 * recovers the recorded press byte.  Only the move byte is
					 * overridden — the MVD-inferred attack/weapon and
					 * back-shift machinery below are left intact.  Skipped on
					 * real .mvd playback (no usercmd to read) and when
					 * usercmd_move is unset (physics move preserved, byte-
					 * identical to the prior force_mvd path).  Mirrors the
					 * matched-emit MLOB co-emission (QNN_RunMatchedEmit). */
					if (qnn_runtime.usercmd_move && !cls.mvdplayback)
					{
						qnn_action_t usercmd_label;
						QNN_QwdBuildActionLabel(&usercmd_label,
							&label_snapshot);
						label_snapshot.action_label.move =
							usercmd_label.move;
						/* op_input is the per-axis operativeness mask
						 * the labeler trains/sanitizes on, and it is a
						 * function of the usercmd press (QwdPackOpInput
						 * reads action->move).  The MVD inference path
						 * never packs it, so without this copy it stays 0
						 * for the whole corpus — which silently turns
						 * --sanitize-targets into "keep only no-press
						 * frames", collapsing every target to the 'none'
						 * class (degenerate 100% acc).  Take it from the
						 * same usercmd decoder as move (matches the
						 * documented usercmd-TRUTH move/look/op_input). */
						label_snapshot.action_label.op_input =
							usercmd_label.op_input;
						qnn_runtime.prev_move =
							label_snapshot.action_label.move;
					}
					snapshot.action_label = label_snapshot.action_label;
				}
				else
				{
					QNN_QwdBuildActionLabel(
						&snapshot.action_label,
						&snapshot);
					QNN_FillLookAndSwitch(&snapshot.action_label,
						&label_snapshot);
				}
			}
			else
				QNN_ClearAction(&snapshot.action_label);

			{
				FILE *emit_out;
				qnn_snapshot_t filter_snapshot;
				uint8_t obs_bytes[QNN_OBS_BUFFER_SIZE];
				int cur_weapon = mvd_path
					? label_snapshot.weapon_id
					: snapshot.weapon_id;

				if (qnn_runtime.force_mvd_emit && !cls.mvdplayback)
				{
					filter_snapshot = snapshot;
					QNN_QwdBuildActionLabel(&filter_snapshot.action_label,
						&snapshot);
					emit_out = QNN_EmitFilter(&filter_snapshot);
					if (snapshot.health <= 0)
					{
						snapshot.action_label.move = 0x01; /* bit 0 = attack press */
					}
				}
				else
				{
					emit_out = QNN_EmitFilter(&snapshot);
				}

				/* QWD path is a pure cmd-byte decoder — action.weapon
				 * is already the canonical label, no rewriting needed.
				 * Only the MVD path runs back-shift inference (weapon
				 * via ping-shift + pickup gate, attack/jump per-event).
				 *
				 * AF restore: pack obs with the start-of-tick
				 * attack_finished (captured before any action label
				 * advanced cooldown). Without this, obs[t] would
				 * contain the post-attack stamp from action[t], leaking
				 * the BC label being predicted into the input. The
				 * agent's live decision-time input is post-prev-action
				 * == start-of-this-tick state; collect must match. */
				{
					float saved_af = QNN_ProgsGetAttackFinished();
					QNN_ProgsSetAttackFinished(
						tick_start_attack_finished);
					QNN_PackSnapshotObs(&snapshot, obs_bytes);
					QNN_ProgsSetAttackFinished(saved_af);
				}

				/* Maintain per-demo running median of svc_updateping
				 * values (used by QNN_PressBackShiftFrames on the MVD
				 * path as a garbage-input fallback). */
				QNN_ObservePings();

				if (mvd_path)
				{
					int prev_weapon = 0;
					qboolean has_prev_weapon =
						QNN_BackShiftPrevWeapon(&prev_weapon);
					qnn_mvd_wtrans_t wtrans = QNN_MVD_WTRANS_NONE;
					int prev_intent = 0;

					/* De-scripted intent label (weapon-head.md §12
					 * parity): the intent machine owns act.weapon
					 * OUTRIGHT — including 0 = unrevealed/masked —
					 * overwriting the held fallback that
					 * QNN_FillLookAndSwitch wrote.  Transition
					 * classification (deliberate / script dump /
					 * forced pickup+ammo-out / death) lives in
					 * qnn_mvd_collect.c; the pickup gate that used
					 * to sit here is the FORCED branch there. */
					snapshot.action_label.weapon =
						(uint8_t)QNN_MvdIntentWeaponStep(
							&label_snapshot,
							QNN_MvdSelectFeasible,
							&wtrans, &prev_intent);

					/* Deliberate adoptions anticipate the press:
					 * rewrite the trailing ring slots from the old
					 * intent, same shift source as the old held
					 * rewrite.  prev_intent==0 slots stay masked —
					 * they may reach into dead frames, which QWD
					 * keeps at 0. */
					if (wtrans == QNN_MVD_WTRANS_DELIBERATE
						&& prev_intent > 0)
						QNN_BackShiftRewriteWeapon(
							snapshot.action_label.weapon,
							prev_intent,
							QNN_PressBackShiftFrames(
								cl.playernum, emit_hz));

					/* Break attack carryover across HELD transitions
					 * (dedup state is held-stream domain, independent
					 * of the intent label): clear the old weapon's
					 * chain state so a later same-weapon shot isn't
					 * false-linked through a different-weapon
					 * interval. */
					if (has_prev_weapon
						&& prev_weapon != cur_weapon
						&& cur_weapon > 0)
						QNN_MvdResetAttackChain(prev_weapon);
				}
				else
				{
					/* Genuine QWD usercmd path: clear a pending weapon lead
					 * the engine never confirms within ~ping×2 frames (a
					 * stale-impulse phantom) by walking the shared ring back
					 * over the lead window — keeps QWD logic out of the MVD
					 * module, reusing QNN_BackShiftRewriteWeapon. */
					QNN_QwdWeaponLeadStep(&snapshot.action_label, &snapshot,
						qnn_runtime.tick,
						QNN_PressBackShiftFrames(cl.playernum, emit_hz),
						emit_hz);
				}

				QNN_BackShiftPush(
					&qnn_runtime.tick_emit, emit_out,
					obs_bytes, &snapshot.action_label,
					snapshot.done,
					qnn_runtime.tick, qnn_runtime.steps,
					emit_hz, false,
					mvd_path ? label_snapshot.grounded
						: snapshot.grounded,
					cur_weapon);

				if (mvd_path)
				{
					/* Attack + jump: per-event back-shift via native_time.
					 * Both use the same ping-RTT correction: sound
					 * arrives at the recording client one full RTT
					 * after the button press.
					 *
					 * No bias correction applied: validation against
					 * direct demo-byte press/sound timestamps on the
					 * fire_lat2 138-demo set shows the engine is already
					 * close to the right operating point with svc_update
					 * ping.  Median residual is −13 ms but the
					 * distribution is heavy-positive-tailed (mean
					 * −1.4 ms), so subtracting a full native period
					 * shifts the bulk too far and net exact-frame
					 * recall drops (76.58 % → 59.06 %).  Reach the
					 * remaining ~6 pp gap to ceiling via per-press
					 * ping (QNN_LatencySeconds on QWD, no alternative
					 * available on MVD playback) instead.
					 *
					 * Must read label_snapshot, not the pre-frame obs
					 * snapshot: QNN_DrainSounds consumes the global
					 * sound ring, and the post-Host_Frame capture
					 * (label_snapshot) is the one that drains this
					 * tick's events.  The pre-frame snapshot's sound
					 * list is always empty — passing it here silenced
					 * every attack/jump event since the pre-frame obs
					 * capture landed. */
					if (label_snapshot.health > 0)
					{
						/* Single ping authority — same source
						 * (median-fallback, outlier-rejected) as
						 * the weapon/move bulk shift via
						 * QNN_PressBackShiftFrames. */
						float ping_sec = QNN_PressPingSec(cl.playernum);
						QNN_MvdBackShiftWriteAttackEvents(&label_snapshot,
							ping_sec,
							qnn_runtime.emit_start_native);
						QNN_MvdBackShiftWriteJumpEvents(&label_snapshot,
							ping_sec,
							qnn_runtime.emit_start_native);

						/* Real MVD: the QC VM never sees cmds, so
						 * W_Attack never stamps attack_finished.
						 * Drive it from detected shots so the obs
						 * attack_finished scalar and the mask's
						 * attack-feasibility bit carry the engine
						 * cooldown. */
						if (cls.mvdplayback
							&& qnn_runtime.native_attack_this_window)
							/* Anchor the cooldown at the back-shifted press
							 * time (now - ping), in lock-step with the attack
							 * bit / weapon / move which are all back-shifted by
							 * ping on this path. Correctness/consistency: the
							 * attack_finished timeline must sit on the same
							 * frame axis as the labels it describes. (Does not
							 * by itself move the operative-attack gap — that's a
							 * separate, still-open issue.) */
							QNN_MvdStampAttackFinished(
								label_snapshot.weapon_id,
								QNN_RuntimeNowSeconds() - ping_sec);
					}

					/* Move: continuous label.  Today's velocity-sign
					 * reflects the keyboard press from `shift` emit
					 * frames ago, so write today's move to the back-
					 * shifted slot. */
					{
						int shift = QNN_PressBackShiftFrames(
							cl.playernum, emit_hz);
						QNN_MvdBackShiftWriteMoveXY(
							snapshot.action_label.move, shift);
					}
				}
			}
			if (!snapshot.done)
				QNN_SaveEmitAnchor(&label_snapshot);

			QNN_SavePrev(&label_snapshot, qnn_runtime.fixed_dt);
		}
		QNN_WatchdogEnd();

		QNN_BackShiftFlushAll(&qnn_runtime.tick_emit);
		QNN_FlushTickEmit(&qnn_runtime.tick_emit);

		if (!qnn_runtime.tick_emit.has_prev_emitted)
		{
			/* Demo ended without emitting any tick — reached
			 * play_end before play_start (degenerate range),
			 * aborted during signon, or replay produced zero
			 * usable frames. Emit a done-tick so the reader
			 * doesn't block waiting for FLAG_DONE. */
			snapshot.done = true;
			QNN_WriteObsTick(&qnn_runtime.tick_emit, stdout,
				&snapshot, qnn_runtime.tick,
				qnn_runtime.steps, emit_hz, true);
		}
		}
	}
	fflush(stdout);
	{
		extern long qnn_dbg_actor_n, qnn_dbg_actor_wirezero;
		FILE *df = fopen("/tmp/qnn_actor_dbg.log", "a");
		if (df) {
			fprintf(df, "actor n=%ld wirezero=%ld\n",
				qnn_dbg_actor_n, qnn_dbg_actor_wirezero);
			fclose(df);
		}
	}
	if (qnn_runtime.store_dump != NULL)
	{
		fflush(qnn_runtime.store_dump);
		fclose(qnn_runtime.store_dump);
		qnn_runtime.store_dump = NULL;
	}
	QNN_FaultSetContext(NULL);
	return 0;
}

int main(int argc, char **argv)
{
	quakeparms_t parms;
	char line[QNN_WORKER_MAX_LINE];

	QNN_FaultInit("qw_demo_worker");
	QNN_ResolveBasedir(qnn_basedir_storage, sizeof(qnn_basedir_storage));
	QNN_RuntimeReset();
	QNN_ClearAction(&qnn_pending_action);
	memset(&parms, 0, sizeof(parms));
	COM_InitArgv(argc, argv);
	parms.argc = com_argc;
	parms.argv = com_argv;
	parms.memsize = 128 * 1024 * 1024;
	parms.membase = malloc(parms.memsize);
	parms.basedir = basedir;
	Host_Init(&parms);
	QNN_TickRegister();

	/* QW's Host_Init runs quake.rc which may connect somewhere.
	 * Disconnect and reset state for worker mode. */
	Cbuf_Execute();
	cls.demonum = -1;
	CL_Disconnect();
	cls.state = ca_disconnected;

	/* Optional: load qwprogs.dat into the server VM and run a smoke
	 * test of the QC VM predicates.  Per-demo QNN_ProgsInit fires from
	 * the "reset" handler; this argv switch lets bring-up validation
	 * run without dispatching a real demo. */
	if (COM_CheckParm("-sanitize-smoke"))
	{
		if (QNN_ProgsInit())
			QNN_ProgsSmokeTest();
	}

	while (fgets(line, sizeof(line), stdin) != NULL)
	{
		/* Match the "op" key precisely — substring search on the raw
		 * line collides with demo filenames that happen to contain
		 * the keyword (e.g. _vs_hello_kitty_).  Looking for the
		 * literal "op":"<value>" pattern (with or without a space)
		 * keeps us schema-tolerant without pulling in a JSON parser. */
		if (QNN_OpIs(line, "hello"))
		{
			QNN_HandleHello(line);
			continue;
		}
		if (QNN_OpIs(line, "nav_query"))
		{
			QNN_HandleNavQuery(line);
			continue;
		}
		if (QNN_OpIs(line, "enumerate_players"))
		{
			QNN_HandleEnumeratePlayers(line);
			continue;
		}
		if (QNN_OpIs(line, "collect"))
		{
			QNN_HandleCollect(line);
			continue;
		}
		if (QNN_OpIs(line, "shutdown"))
		{
			fprintf(stdout, "{\"ok\":true}\n");
			fflush(stdout);
			QNN_FreeMapState(&qnn_map_state);
			Host_Shutdown();
			return 0;
		}
	}

	QNN_FreeMapState(&qnn_map_state);
	Host_Shutdown();
	return 0;
}
