services:
  qnn-live:
    image: ${QNN_LIVE_IMAGE_TAG:-qnn-live:amd64}
    platform: linux/amd64
    build:
      context: ../..
      dockerfile: src/docker/Dockerfile.live
      platforms:
        - linux/amd64
    working_dir: /app
    volumes:
      - type: bind
        source: /app/bin
        target: /app/bin
        read_only: true
      - type: bind
        source: /app/models
        target: /app/models
        read_only: true
    stdin_open: true
    tty: true
